### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/sedaily-front-end#1]
From Slack SWXY:
```
every episode happens to be linking to https://sedaily.herokuapp.com/#/item/undefined right now, think u changed the datamodel and didnt update this frontend
```

**Comment by jasonify** [comment]
I can't assign this to myself but it seems like a  _id vs id issue. It is getting resolved on my fork of the project. 

I haven't looked into it much more than to fix my build so I could get working on this.


I doubt it matters for this issue but  I also don't have redis / docker setup properly. I'll investigate further, later. 


For reference it's line 16 of this file:

https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/master/src/components/Item.vue



What's odd is that it wokrs on the heroku site (though the api still returns _id and not id).

**Comment by TheHollidayInn** [comment]
Yea, that's the issue. If you want to open a PR with just that, we would be happy to take it :D

**Comment by jasonify** [comment]
Fixed as part of this PR https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/23
