### ISSUE TITLE
Fix Social Sharing

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#104]

**Comment by jasonify** [comment]
This would be nice to investigate.

Though, I imagine it might be more complicated than we think. My assumption is that it might require server side rendering like it has in the past. Unless their bots have evolved.  

Also, twitter and facebook have validators: https://cards-dev.twitter.com/validator

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjagLWRk8HXAhVO62MKHc5YDRIQFggoMAA&url=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fdebug%2F&usg=AOvVaw1Wodj1wY7330LWPM5KGNX_

**Comment by crablar** [comment]
More details on sharing issues:

- Remove “Facebook” “LinkedIn” “Twitter” and just leave logos of the social
- Make mouseover on the logos turn mouse into cursor to share
- LinkedIn sharing broken
- Make featured images get shared along with the link
- Shared link is just softwaredaily.com/# when it should share a link to the actual episode
-

**Comment by crablar** [comment]
No.
