### ISSUE TITLE
componentize and align voting arrows

### ISSUE THREAD

**Issue by itaykomemy** [SoftwareEngineeringDaily/sedaily-front-end#152]
They appear in four places:
PostDetailsView
RelatedLink
PostSummary
CommentView

I think it's worth-while to make them a component (and fix alignment)

![image](https://user-images.githubusercontent.com/2780526/34328951-86e75360-e8f7-11e7-8b72-20e4f3f2de0a.png)

**Comment by itaykomemy** [comment]
@jasonify Can you assign it to me ?

**Comment by crablar** [comment]
@itaykomemy got it. Good first issue--though @jasonify is working on a redesign of the website when he gets back, to make it look nicer.
