### ISSUE TITLE
Related Links Automatic Titling

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#208]
Have related links automatically grab a title and recommend it based on URL

For an example, look at a [post](https://www.softwaredaily.com/#/post/5a61c24b34fd510004cefe92/Service-Mesh-Design-with-Oliver-Gould). If the user adds a URL, we should automatically grab a title from the URL and suggest that for the title of the related link (but also give user the option to write their own)

**Comment by crablar** [comment]
@tyler-furby would you have time to take a look at this one in the next few weeks?

**Comment by tyler-furby** [comment]
I’ll take a look at this!
