### ISSUE TITLE
Save images to S3 to get HTTPS Green Lock

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#209]
Save all images across the site to S3 and serve them from S3 to fix our HTTPS

**Comment by andrewmarklloyd** [comment]
I think the work for this is done in https://github.com/SoftwareEngineeringDaily/sedaily-miner right?

**Comment by crablar** [comment]
Unfortunately not. The images on posts, for example: https://www.softwaredaily.com/#/post/5a6afc6a30e9ec00045e4765/Edge-Deep-Learning-with-Aran-Khanna

**Comment by andrewmarklloyd** [comment]
Oh those images are embedded in the html of the post?
