### ISSUE TITLE
Combine "New", "Top", "Recommended" Into 1 Dropdown

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#210]
Change it to say "Podcast" and be underlined. When user hovers over it, there is a dropdown of New, Top, Recommended menu, but the user can also just click "Podcast" to go to /#

**Comment by crablar** [comment]
@dfcook @jasonify what do you think of this?

**Comment by dfcook** [comment]
I wasn't sure how this would look but tried it and think it's definitely tidier.

Raised pull request.
