### ISSUE TITLE
Crowdsource Better Tagging

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#212]
Users should be able to add/remove tags to episodes, but only pick/search from the tags we have already added

**Comment by jasonify** [comment]
Not sure I am following 100% on this one. So there is the "main tags" that we add ourselves and search from those? 

Purpose of user defined tags: when you click a user added tags it would show those episodes with that tag?

**Comment by crablar** [comment]
That's right. Similar to [what Quora does with "Edit Topics"](https://www.quora.com/What-is-the-longest-amount-of-time-you-have-spent-fighting-a-code-bug#)

This issue is not big priority but would help with labeling.
