### ISSUE TITLE
Clarify testing process

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#221]
Hi - mentioned on Slack but figured I should formalize this issue.

README.md currently includes:

```md
# run selenium tests (working)
npm run selenium-test
```

However, files in `test/selenium` and the related `test/helpers` haven't been updates in 3 months.

On the other hand, `test/e2e` (itself a selenium abstraction using nightwatch) and `test/unit` have been updated and seem active parts of the project. 

My proposal:

* Remove `test/selenium` and `test/helpers` as well as the references in `package.json` and `README.md`.
* Update to reference README.md but also provide some guidelines on what functions should be tested and how

**Comment by jasonify** [comment]
Sounds good to me.

**Comment by joshmorel** [comment]
So I'm going to blow away the `test/selenium` and `test/helpers` and update the readme.

However, I'd like to provide (and get) some guidelines on what exactly to test. Like are we just testing business logic type stuff or unit test all Vue components?

**Comment by crablar** [comment]
I'd prioritize business logic
