### ISSUE TITLE
Remove console logging

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/sedaily-front-end#227]
There is logging on production that should be removed. See attached screenshots:

![screen shot 2018-01-25 at 1 13 06 pm](https://user-images.githubusercontent.com/7810418/35412604-870dd3c6-01d1-11e8-9dc4-27bb2d0f47d6.png)

![screen shot 2018-01-25 at 1 11 16 pm](https://user-images.githubusercontent.com/7810418/35412538-5b3e2638-01d1-11e8-9384-e3a0bd6a0aac.png)

![screen shot 2018-01-25 at 1 05 40 pm](https://user-images.githubusercontent.com/7810418/35412564-667f6584-01d1-11e8-8c8b-a85ea3044edd.png)

**Comment by andrewmarklloyd** [comment]
@jasonify this is probably a "good first issue", I just can't add labels

**Comment by EmilyRosina** [comment]
Does this mean you're not minifying the code for production?
As I believe you can pass the option to webpack to remove `console.log`s on build.
