### ISSUE TITLE
Padding on smaller widths is 0

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#229]
![screen shot 2018-01-25 at 4 15 00 pm](https://user-images.githubusercontent.com/150265/35419091-f699ac56-01ea-11e8-9637-277cc3c9a4ae.png)

Should be add a little padding on both sides

**Comment by dfcook** [comment]
Is the problem the missing border on "All", I've tried different resolutions and can't reproduce this, when it looks like it's about to clip the border it switches to a horizontal scrollbar. Tried on chrome and firefox.

**Comment by jasonify** [comment]
Ahh sorry that was just a bad screenshot. It's a problem of all the content being too close to the edges. The border is still there though
