### ISSUE TITLE
Error with "filtered" property on Jobs list

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#252]
Getting this:
vue.esm.js?efeb:578 [Vue warn]: Property or method "filtered" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <JobsBoardView> at src/views/JobsBoardView.vue
       <App> at src/App.vue
         <Root>

**Comment by jasonify** [comment]
@joshmorel  not sure if it's related to the jobs list / search

**Comment by joshmorel** [comment]
I see the issue in the code although the functionality was working as expected. I'll troubleshoot tonight and fix. Adding test coverage this weekend will help with more clearly showing the intent :slightly_smiling_face:
