### ISSUE TITLE
Adding a Job: If remote is clicked, error for missing location could be nicer

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#254]
Maybe to ask: "You can put your company's headquarter location or Worldwide"

**Comment by joshmorel** [comment]
Hey @jasonify I'm also wondering if a longer term re-usable input error component would be helpful, which could include a message prop.

We could then have a consistent behavior as well and more easily change that for the entire app when future design decisions are made.

**Comment by gmemstr** [comment]
I'm going to look into this :)

**Comment by jasonify** [comment]
@joshmorel  we totally need that, I believe there is an issue for removing our alert errors / msgs / warnings which would go hand in hand with that.
