### ISSUE TITLE
Clean up UI on /add-job  (job type)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#255]
Just need some spacing between radio button + text
<img width="992" alt="screen shot 2018-02-21 at 1 29 17 pm" src="https://user-images.githubusercontent.com/150265/36506406-66a73a6a-170b-11e8-838f-f61477fab401.png">

**Comment by gmemstr** [comment]
Fixed in my fork, PR coming soon once I fix a few other issues.
