### ISSUE TITLE
Playback speed indicator should show current speed

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/sedaily-front-end#265]
Playback speed indicated on the player should show the current playback speed, instead of the speed that will be changed to. This would be consistent with the iOS UI

![screen shot 2018-02-24 at 8 25 02 am](https://user-images.githubusercontent.com/7810418/36632498-466cb2ce-193c-11e8-9b94-fdc2e4640748.png)

**Comment by jasonify** [comment]
Agreed 👍
