### ISSUE TITLE
Refactor comments mutations into its own file

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#27]

**Comment by andrewmarklloyd** [comment]
Is it a good idea to refactor a lot of the functions to their own files?

**Comment by crablar** [comment]
I think there are some Vue best practices around the right way to do this. @jasonify and I were talking about it back in October.

**Comment by jasonify** [comment]
I think as the app grows it makes sense to break out everything from one giant file. Maybe not as much for mutations just yet. 

I like the fact that this would mirror other parts of the app and backend.
