### ISSUE TITLE
Fails to build with Yarn

### ISSUE THREAD

**Issue by gmemstr** [SoftwareEngineeringDaily/sedaily-front-end#272]
I'm going to do a little digging myself but I can't seem to use yarn for running the dev enviornment. npm works fine.

```
# This doesn't work
yarn install

yarn run dev
```

**Comment by jasonify** [comment]
Yeah, we should at least remove that from the repo until it's fixed

**Comment by dfcook** [comment]
Can you let me know what error you are seeing? I use yarn to run the app all the time without any issue.

**Comment by gmemstr** [comment]
Might have been Windows specific (or some other snafu) so closing for now.
