### ISSUE TITLE
HTTPS Redirect Failing

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#275]
https://softwaredaily.com/ -> 404

**Comment by gmemstr** [comment]
Weird becasue when you remove the HTTPS part it seems to redirect back to HTTPS just fine. Only seems to occur when directly visiting the HTTPS version.

**Comment by joshmorel** [comment]
This is a DNS issue. I think you need to add a CNAME entry from softwaredaily.com to www.softwaredaily.com.
