### ISSUE TITLE
Require job type to be selected (radio buttons for Permanent or Contract) on New Job Form

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#280]
I believe someone hit this today, the server seems to be returning a 500 and the frontend isn't validating for this. 

Backend will require a little investigating too I think, logs seem to show it does fail on the validator but is throwing a 500 and the frontend is not displaying anything useful to the user.

**Comment by jasonify** [comment]
Let me know if either of you might have a chance to look into this @dfcook  @joshmorel

**Comment by joshmorel** [comment]
Thanks @dfcook
