### ISSUE TITLE
On empty comments for a post, show something to encourage users to register / create comments

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#282]
'No comments yet, be the first to comment, register here'

'No comments exist yet, comment here.'

Something like that, maybe just the comment form.

**Comment by PaulTFreedman** [comment]
Can you link to a page that has comments please? I'm having trouble finding one that has any!

**Comment by jasonify** [comment]
I would recommend pulling the backend locally and adding comments there, would allow you for the most flexibility for this feature.
