### ISSUE TITLE
yarn.lock or package-lock.json

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#283]
I don't think we want to update both `yarn.lock` and `package-lock.json` because keeping both up to date is not automatic. I'd suggest we [adopt one as the official package manager](https://stackoverflow.com/a/44904494/4582054) for this project. I'd prefer `npm` because we've been using it all along without issue but am open.

**Comment by jasonify** [comment]
I also vote for `npm` or the same reasons.

**Comment by edgar971** [comment]
Let's stick to the package-lock.json file. Yarn was only needed for the lock file which NPM didn't support before. Also, one less dependency.

**Comment by gmemstr** [comment]
I'm personally partial to Yarn because of how it handles installation of new modules, but I'm okay with switching to npm.

**Comment by edgar971** [comment]
Many of the features Yarn includes are now in the latest version of NPM. I used Yarn for the same reasons but im starting to move away from it.
