### ISSUE TITLE
Investigate heroku's auto watch / restart system?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#288]
Since the site crashed and stayed down for a little while (at least a few minutes) but came back online on it's own later, maybe heroku has something in place? It crashed and came back online more than once.

This was for the `nuxt` branch. 

Note staging is currently on a free dyno.
<img width="1090" alt="screen shot 2018-03-08 at 11 35 25 am" src="https://user-images.githubusercontent.com/150265/37232760-324d6658-23a5-11e8-9ce5-c4fdbd4c119f.png">

Th

**Comment by edgar971** [comment]
Dynos running on Heroku are cycled at least once per day .
