### ISSUE TITLE
Contributors page returns an error

### ISSUE THREAD

**Issue by gmemstr** [SoftwareEngineeringDaily/sedaily-front-end#292]

**Comment by jasonify** [comment]
What's the error?

**Comment by gmemstr** [comment]
Just "an error occured". Haven't had a chance to check in my local environment. Also noticed whenever an error occurs or a page is not found it defaults to the "Open positions" view with no content.

**Comment by jasonify** [comment]
Hmm that's strange, I tried to reproduce but couldn't get that error, is it an alert?

**Comment by gmemstr** [comment]
Heroku domain:

![image](https://user-images.githubusercontent.com/1878840/37363315-d3184596-26b4-11e8-82a8-e3472b0554d2.png)

softwaredaily.com:

![image](https://user-images.githubusercontent.com/1878840/37363375-0221efcc-26b5-11e8-9048-06f9ef8adb53.png)

localhost apparently works fine so I'm not sure what's going on

![image](https://user-images.githubusercontent.com/1878840/37363598-8cadac80-26b5-11e8-8868-537e987b5a27.png)

**Comment by jasonify** [comment]
Ah yeah that just means it's not pushed to prod yet (usually we ship pretty quickly so I understand the confusion).  

To verify: Prod also  also has the old msging for the Contribute to Github and no link to the contributors page.
