### ISSUE TITLE
Add tagging to jobs board

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#296]
Or labels/categories.

Discuss here preferences. 

* Tags like [remoteok](https://remoteok.io/)
* Categories like [nofluffjobs](https://nofluffjobs.com/)

If we use tags we can cross-link with episodes once we build this out more for both so this may be the better choice. We can also add both at a certain point, but we should start with one.

**Comment by mkunikow** [comment]
Yes it would be nice if you could filter labels, criteria for example `blockchain, warsaw` -> this would search for all blockchain jobs in warsa
