### ISSUE TITLE
Make staging deploy command take the current branch and push to staging instead of always using the same branch

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#301]
In package.json
`    "staging-deploy2": "git push staging `git subtree split --prefix dist master`:master --force",`

Changing that push the current branch up to heroku.

Example to push develop branch to heroku is:
`    "staging-deploy2": "git push staging `git subtree split --prefix dist develop`:master --force",`

But making it the current branch would be best :)

**Comment by andrewmarklloyd** [comment]
No longer necessary as deployments are built in Heroku
