### ISSUE TITLE
/api/users/undefined request in login and register

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#307]
When navigating to `/register` or `/login` a request is sent to `/api/users/{userId}`, however, when the user is not yet logged this is `/api/users/undefined` which always results in a 500 server error.

I see this was introduced in  81e94feb5825b2ff9ee670583f60a83c33c38ad9 and 81e94feb5825b2ff9ee670583f60a83c33c38ad9 by adding `fetchPublicProfileData` to the views. I see the need for the change to check for `isLoggedIn` but is this additional request necessary?

Also, if it is and just for general purposes - tackling issue #239  would be a good idea. I'm up to do it unless someone wants to take it on.

Options are:

1) remove the `fetchPublicProfileData` calls in both views
2) implement resolution to issue #239 so that any call to get profile is only done at point of authentication (login, register or on loading localStorage)
3) First 1 then 2

**Comment by joshmorel** [comment]
Found a pretty elegant solution that will resolve this as well as the other issue using `store.watch`. Just need to refactor all the places where `fetchMyProfileData` and ensure nothing breaks! I'll have a pr maybe tomorrow or Tuesday.

**Comment by gmemstr** [comment]
Yeah, sorry about that extra call - it was the easiest way to implement the check, since it already existed elsewhere in the codebase.

**Comment by joshmorel** [comment]
No worries - not a huge impact anyways... but shouldn't the `IsLoggedIn` getter be good enough?

**Comment by gmemstr** [comment]
Somehow completely missed that - oops. Still pretty new to this codebase 😛

**Comment by joshmorel** [comment]
Totally understandable :slightly_smiling_face: 

Just starting to get a handle on the whole thing now myself.

**Comment by joshmorel** [comment]
Resolved by #315
