### ISSUE TITLE
Comment Upvote UI is not updating right away

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#309]
Should be reflected on the frontend after doing an upvote. On refresh it works fine so not a server issue.

**Comment by EmilyRosina** [comment]
It does currently on develop (takes a second or two after click)

### Before
![image](https://user-images.githubusercontent.com/21045073/39013733-3b74f88c-4410-11e8-8f95-bb9f5b0673cb.png)

### After
![image](https://user-images.githubusercontent.com/21045073/39013766-502d2e2a-4410-11e8-8659-ccb4e3947b60.png)
