### ISSUE TITLE
Create "Manual Rundown Test Script" file: ManualTestinChecklist.md

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#314]
Should include all key actions to manually test for big PRs.

register, login, logout, edit profile, create job, subscribe, play podcast, etc.

Put at root of directory, i.e `ManualTestinChecklist.md`

**Comment by dfcook** [comment]
Initial thoughts (added to my PR)

## Forum
1. View existing forum posts (logged out/in)
2. Create new forum post.
3. Reply to existing forum post.
4. Delete reply.

## Jobs
1. Check jobs link is available when logged out or in
2. List of jobs is displayed when clicked on link
3. Can click on jobs and see details.
4. Can apply to job when not the poster of the listing.
5. Apply validates and submits successfully.
6. If poster of job can edit job.
7. Updates to job processed successfully.
8. Job delete processed successfully.
9. When logged in can add new job.
10. Job add is validated and posts successfully.

## Post lists
1. View main page list (logged out/in)
2. View New list (logged out/in)
3. View Top list (logged out/in)
4. View Recommended list (logged out/in)
5. Play episode from main page.
6. Upvote post
7. Downvote post
8. Click on categories

## Post detail
1. Load post, view detail.
2. Play episode from detail screen.
3. Upvote post
4. Downvote post
5. Add comment
6. Reply to comment
7. Delete reply
8. Delete comment
9. Add related link
10. Remove related link

## Player
1. Play episode
2. Move slider to move to position in episode
3. Toggle pause
4. Toggle 1.5 speed

## Register
1. Check register link is available when not logged in.
2. Complete registration form and check logged in when submitted

## Login
1. Check login link is available when not logged in.
2. Check successful login navigates correctly.
3. Check unsuccessful login displays appropriate error.

## Logout
1. Check logout link is available when logged in.
2. Clicking logout clears profile and link reverts to login.

## Profile
1. Check profile link available when logged in.
2. Check clicking link takes to profile view.
3. Can click on edit profile.
4. Changes to edit profile are visible in profile view.
