### ISSUE TITLE
 Crashing Chrome often. Memory leaks?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#32]
@crablar  mentioned this happens to him often when developing

Could be due to the nature of live code reloading while developing? Haven't really noticed this as an issue.

**Comment by crablar** [comment]
I have a lotta chrome extensions too

**Comment by joshmorel** [comment]
I think this might have to do with the A-Player downloading all the mp3s prior to playing. This wouldn't be a problem with a few but the main view is a decently sized array of APlayers.

If you really want the mp3 playable from the main view I think we'd want to not use the `preload` default of `'auto'` -   https://aplayer.js.org/docs/#/?id=options

![sed-chrome-network](https://user-images.githubusercontent.com/10546720/31820365-fe79e9fe-b56e-11e7-9fe0-030957fef66e.png)

**Comment by TheHollidayInn** [comment]
I think we should only have a single play like the mobile apps. That would be more performant and correspond with normal UX

**Comment by jasonify** [comment]
:) Agreed, and that's what this new branch is doing:   `global-player-WIP` which is why it was odd since I think Jeff was having problems even after we removed all the player objects.

**Comment by TheHollidayInn** [comment]
Ah! I didn't see the branch. Awesome :D
