### ISSUE TITLE
Sometimes posts dont load if the window is too small -- pagination issue?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#322]
My theory is that it has something to do with our pagination of posts being a little weird and not loading any posts if the window is too small.

**Comment by jasonify** [comment]
@dfcook  have you seen this happen, any ideas?

**Comment by dfcook** [comment]
I haven't, however there are quite a lot of open issues for vue-infinite-scroll talking about screen size:

https://github.com/ElemeFE/vue-infinite-scroll/issues

Package hasn't been updated for 6 months, perhaps it may be worth looking at alternatives or building our own.

**Comment by jasonify** [comment]
Ah, yeah, I guess we might need our own if no alternatives exist.
