### ISSUE TITLE
#Forum, improve Style + Flow

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#328]
We want to improve the look and feel the forum to match closer to the mocks here. 

We also want to refactor the forum-post creation to be it's own page. There is  a separate issue for adding markdown support too: https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/327

![forum list copy 39](https://user-images.githubusercontent.com/150265/37859068-62d33e16-2ecb-11e8-9aaf-a0f89f620ede.png)

![create post copy 5](https://user-images.githubusercontent.com/150265/37858428-bb01bb58-2ec1-11e8-8d22-d3349fccd6dd.png)
![forum post copy 20](https://user-images.githubusercontent.com/150265/37858430-bb2f68be-2ec1-11e8-8e86-52f938d3dfdc.png)
![markdown info copy](https://user-images.githubusercontent.com/150265/37858431-bb479628-2ec1-11e8-8ef0-29d44ae99b58.png)

**Comment by tyler-furby** [comment]
I can work on improving the style of this, starting with fonts
