### ISSUE TITLE
Forum: Users without a Name should be encouraged to fill one in (but not annoyed)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#333]
Something maybe at the top of the forum compose form or when viewing a thread?  Maybe just site wide?

Maybe after you make a comment / post you are redirected to add a name if you like? Otherwise continue to where you were supposed to go.

Saying something like "It looks like you haven't updated your profile with your name which is used when you post, change it here"

The check would be `user.name.indexOf("Software  Developer") >= 0`  since we default to setting that as a name for people that didn't have one (now required on registration).

**Comment by andrewmarklloyd** [comment]
The redirect is a good idea, simple and effective I think
