### ISSUE TITLE
Limit file size of profile pictures

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#339]
We don't want them to be huge since we don't process them on the backend yet.

**Comment by dfcook** [comment]
Could we look at a backend fix for this and the post images? I think some of those are huge and are impacting the load of the main page, if we could have a server-side resizing that would increase overall performance.

**Comment by jasonify** [comment]
Hmm we might be able to and that's truly the real solution we want but I am not sure heroku is super friendly to image uploads so wanted to keep it off the server. 

It seems that some modern APIs for the webbrowser allows this.

Eventually we could probably write a script to resize / crop avatars that are too large.
