### ISSUE TITLE
Not showing the linter errors anymore?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#340]
I know they are in the console but I kinda liked that they would auto refresh when fixed and so leave no trace when they took over the HTML. The benefit was being able to quickly tell at a glance if it was broken or not. Now the errors remain in the console.

**Comment by jasonify** [comment]
@dfcook  what do you think? I don't think it's a big deal either way but now I kinda miss the overly annoying linter errors in your face.

**Comment by dfcook** [comment]
Is this just that webpack isn't clearing the screen on rebuild, so is leaving stale linting errors in the console?
