### ISSUE TITLE
I am seeing styling / display differences between the build results and the dev server

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#344]
This makes it pretty difficult to style things. 

To replicate, use this commit for reference (latest in develop right now: https://github.com/SoftwareEngineeringDaily/sedaily-front-end/commit/50b282e5258c05fbe448d3a7708eba31c9e4ab80)

Then in the forum, create a few comments. Compare the way it looks to when you run `npm run dev` vs `npm run build-staging && npm start` -> runs on port 5000

 @dfcook  I think that was introduced recently with either the webpack upgrade or an incorrect merge on my part. Though I wonder if it's always been there just never noticed it.

**Comment by dfcook** [comment]
This looks like merge issues, the index.html is still pulling in css and js from the cdn when they are now being resolved by webpack.
