### ISSUE TITLE
Creating New Comments should show "processing" indicator & show nice errors  

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#36]
No indicator that comment is still processing currently. Should also not show alert on failure but a nicer message inline with the fake comment, maybe even a "Retry" button.

Note, make sure to handle multiple dummy comments correctly.

**Comment by TheHollidayInn** [comment]
Why does the comment process? Can you not add a local copy and send the comment in the background?

**Comment by jasonify** [comment]
Yeah that's what's currently happening. 

What I mean is that it should probably still do that but also say "posting....." and "done" when it eventually is done. If it fails it should let you retry or at least show that it failed with some type of visual indicator in the dummy comment.

**Comment by TheHollidayInn** [comment]
Ah, okay. I like that idea. A very granular loading
