### ISSUE TITLE
MailChimp Error Preventing Registration

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#366]
This is in prod. Steps to reproduce:
1. go to register a new account
2. make sure "Signup for newsletter?" is checked
3. click to register

Page errors out with "MailChimp error" and takes you back to homepage.

**Comment by jasonify** [comment]
I deployed a hotfix for now. 

It's quite strange because it works on staging but not prod, so I am guessing it's an incorrect KEY/secret issue. Regardless, incorrect credentials should not cause this problem, so I'll have to investigate this further.

**Comment by crablar** [comment]
Adding @gmemstr in case he has ideas

**Comment by gmemstr** [comment]
This is really weird, what variation is there between staging and production?

**Comment by jasonify** [comment]
One of the differences are the keys, one is my own test set, used on staging...

I'll have to investigate further and see if they are running the same version of the server + why it's failing when keys are wrong since we have a safeguard around that.

**Comment by jasonify** [comment]
Looking at the way the error is handled for mailchimp, I'm seeing part of the problem, which is that we are calling next, which what we should really be doing is just setting newsletter to false and allowing the registration to continue instead.

**Comment by andrewmarklloyd** [comment]
Anything to do with this? https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/commit/debeeb6a80f9a8ed57ff8a3ebcfbba2d98b25534

**Comment by andrewmarklloyd** [comment]
@jasonify @crablar @gmemstr I'm making changes to how we're sending errors to the API. I can add a fix for this issue

**Comment by andrewmarklloyd** [comment]
Working on the fix here: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/pull/193

**Comment by andrewmarklloyd** [comment]
I can't recreate the issue locally. It fails with the Mailchimp error but a new user is created and I can login fine.

**Comment by jasonify** [comment]
Yeah a user is created even though it fails which is interesting.

**Comment by andrewmarklloyd** [comment]
But the user is only created on staging and not production right?

**Comment by jasonify** [comment]
On staging everything works fine (user is created and there is no error). On production is what I'm taking about.

**Comment by jasonify** [comment]
I've fixed this.
This was a combination of two things: 

1) next should not be called if the newsletter fails because it would exit the registration process
2) The api key on production for mailchimp in heroku was wrong.

Even if our API key is wrong, we don't want to prevent people from registration though so have fixed that now.
