### ISSUE TITLE
Make the date format look nicer.

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#4]
Part of an item view. Requires further exploration of `moment` docs

**Comment by edgar971** [comment]
Hi, I'll take this one. Is there a specific format we want it to display it as? Like YYYY, MM, DD?

**Comment by crablar** [comment]
Like "October 17, 2017"

**Comment by edgar971** [comment]
Done, I submitted a PR into staging. Is that right?

**Comment by jasonify** [comment]
Thanks for fixing this 👍 💯
