### ISSUE TITLE
Activity Feed Brainstorm

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#449]
![profile copy 12](https://user-images.githubusercontent.com/150265/38964663-e5efc466-432c-11e8-8254-369d0f6623d6.png)

**Comment by crablar** [comment]
Nice work.

**Comment by crablar** [comment]
@tyler-furby any suggestions?

**Comment by tyler-furby** [comment]
This looks pretty good, I think we should implement the mock-up with those social accounts and an about paragraph, and for those who post project ideas, we can find a way to implement those as well, perhaps above the recent activity feed?

**Comment by tyler-furby** [comment]
What do you think? Albeit, the numbers under the graph will be primary color I think.

![profile copy 12](https://user-images.githubusercontent.com/18516968/39087154-23ec6e48-455a-11e8-85a4-5473df54a025.png)

**Comment by crablar** [comment]
Tyler this looks amazing. Nice work.
