### ISSUE TITLE
Forum titles max width is a bit short

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#466]
<img width="1156" alt="screen shot 2018-04-20 at 1 54 44 pm" src="https://user-images.githubusercontent.com/150265/39073384-7333b898-44a2-11e8-97f9-a6e29b0481d1.png">

It fixes itself if I scroll down to a post that has even a longer title.. very strange

**Comment by tyler-furby** [comment]
Fixed this in #469
