### ISSUE TITLE
Tweak Episode Page Design Look and Feel

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#475]
The current design for episode pages have a few clear issues and some more subtle ones ([example here](https://www.softwaredaily.com/post/5913c0974ee01db33caccef0/Data-Engineering-with-Pete-Soderling)): 
- "Sponsors" takes up way too much real estate
- the Related Links and Comments bars on the side are interesting but perhaps too cluttery, and I don't like the text at 90 degree angle
- "Comments" should be more prominent, as we have connected Forum and Comments
- Comments and related links shouldn't be parallel to each other, also feels cluttered

**Comment by crablar** [comment]
Would love your ideas @EmilyRosina @tyler-furby

**Comment by tyler-furby** [comment]
Thanks for opening this issue up, @EmilyRosina what are your thoughts about this? Do you want to collaborate on getting a mock-up designed for the episode pages?

**Comment by EmilyRosina** [comment]
Just adding some ref images to aid spitballing from within this issue 👍 

# Web
![image](https://user-images.githubusercontent.com/21045073/39243647-160628ee-4886-11e8-949d-c7420a2a0a71.png)

# Mobile
![image](https://user-images.githubusercontent.com/21045073/39243836-b449c4e8-4886-11e8-9d81-a3ff22efe431.png)
![image](https://user-images.githubusercontent.com/21045073/39243816-a2ecfa9e-4886-11e8-9907-86d0fa14d84a.png)

**Comment by EmilyRosina** [comment]
A few thoughts to get ball rolling..

- Sponsors are too big on both **web** and **mobile**, but they feel gigantic in **mobile** particularly
- Need to fix the link to that img/icon that can't be found
![image](https://user-images.githubusercontent.com/21045073/39244851-e0d1d110-4889-11e8-8a16-ca13b5779b0a.png)
- Each of the social links should have their own line, or at least take their icon with them on wrap (it looks a little disorganised)
![image](https://user-images.githubusercontent.com/21045073/39244872-f1bdec98-4889-11e8-99e1-39cddf98fa07.png)
- The icons below the play bar should have tool tips to suggest what they are (especially as the last 2 link to `Related Links` and `Comments`
![image](https://user-images.githubusercontent.com/21045073/39244834-ce48ccb0-4889-11e8-9374-8f3690e6e042.png)
- Further to my last point, if we did away with the side bar (vertical text) we could count related links and comments with a badge/tag, if the count is important
- The detail text should be bigger/more prominent
- Looking at other media players (youtube, TED, various podcast websites), each of these posts/podcasts would benefit with an image, and I can see we're using a small one behind the play/pause once we click play in the main bar - could we use a bigger version of this?
![image](https://user-images.githubusercontent.com/21045073/39244941-2633ccf4-488a-11e8-9fdb-b28cb2916080.png)
- ❔ what are `related links` and how are they used? (i.e. are they dynamically added using similar named/tagged posts, do we add them manually, do users add these?)
---
- It may be a general thing, but the way the nav-bar wraps is a little messy and misleading, i.e. it could be misconstrued that we're on the jobs section of the website (as it looks like a subtitle on the **mobile** view
![image](https://user-images.githubusercontent.com/21045073/39244893-fe9caa44-4889-11e8-9c1a-35e51f3ca110.png)

**Comment by crablar** [comment]
A good reference point: https://www.indiehackers.com/podcast/051-rand-fishkin-of-moz-and-sparktoro

There is one direction to look--downward scroll. There is no place where two items are side by side. We should replicate this, and have a related links section above the comments section.
