### ISSUE TITLE
GitHub Contributions on Profile Pages

### ISSUE THREAD

**Issue by tyler-furby** [SoftwareEngineeringDaily/sedaily-front-end#480]
I was working on getting GitHub contributions up on the profile page, should we create a specific vue.js npm package for this? I was originally thinking about importing an external script, and it seems to work fine, but for the purposes of maintaining for the future, it could be a little sloppy.

Here's a mock-up with this integration:
![image](https://user-images.githubusercontent.com/18516968/39158432-45a6e0c6-471d-11e8-90c9-72c890e739e6.png)

@joshmorel @dfcook @andrewmarklloyd @jasonify 

```
mounted: function() {
      let gitHubCalenderScript = document.createElement('script')
      gitHubCalenderScript.setAttribute('src', 'https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js')
      gitHubCalenderScript.async = true
      document.head.appendChild(gitHubCalenderScript)

      GitHubCalendar(".calendar", userData.github, {responsive: true})
}
```

**Comment by andrewmarklloyd** [comment]
That doesn't look bad, what would you do differently?

**Comment by joshmorel** [comment]
I really like it. 

I don't think we need a Vue specific package. I think the best practice would be to [install with npm](https://github.com/IonicaBizau/github-calendar#cloud-installation) and require it like any other module in a Vue component. This component would then be used within the profile page.

**Comment by tyler-furby** [comment]
Sweet, thanks for the input, @joshmorel that's a better idea, I had this function just mounted to the ProfileDetails component. Putting it in it's own component would make a lot more sense, I'll go ahead and do that instead. Thanks!
