### ISSUE TITLE
Related Links Gamification

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#482]
We would like to encourage people to add more related links to the episodes. This will create a durable knowledge resource around the episodes.

If we also add the related links that a user posts to that user's profile, it could create an interesting history of what that user has been reading/sharing (sort of like how it used to be cool to scroll through someone's Facebook wall to find interesting links they had shared).

I'd love some ideas around how to gamify this.

**Comment by crablar** [comment]
There are ~700 episodes. I estimate there are at least 4 interesting links that can be associated per episode. That's a total of 2800 links we need to crowdsource. 

If we did a contest where anyone who adds 50 quality links gets an SE Daily hoodie, that would cost us ~$1600 if we filled the 4 link per episode quota.

We would have to do some sort of quality control if we wanted to push people to crowdsource like that, so I'm not sure that is the right approach.

This is why I like the idea of having some UI elements that encourage people to post links, that also adds the links to their profile. So they feel that their reputation is attached to the quality of links they are sourcing.

**Comment by andrewmarklloyd** [comment]
The links could be weighted by number of upvotes, which could help quality control them. So if a person adds 2 related links to a given episode, there's 2 points. Then every upvote per related link is another point. This would be similar to Reddit karma. So if each one of those 2 related links gets 10 upvotes each, then the person has a total of 22 points.

That way people aren't completely reliant on people upvoting the links to get points, but they do help earn points.

**Comment by crablar** [comment]
I was warned by someone at a popular social network that had credits/karma before deprecating them. They said it created huge technical debt, because every part of the application had to be wired into it.

**Comment by joshmorel** [comment]
I wonder... is there a happy medium? I think people would respond to a simple reputation system based on upvotes.

If you want to reward with actual goods, an option would be one-off campaigns where you'd ask people to, let's say, add 10 legit related links in May and make a tweet with a specific hashtag and send an email with address etc. This could be verified via Twitter and a simple database query and you wouldn't add any technical debt to the app itself. It would take some manual work of course, but nothing too onerous I image.
