### ISSUE TITLE
Remove sponsors from post page

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#486]
We can remove the "sponsors" entirely from the posts on Software Daily. Our contracts with sponsors only extend to Software Engineering Daily. Ideally we should keep the Sponsors in the data model.

RE: https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/475#issuecomment-385384016

**Comment by crablar** [comment]
Yes, would love to see this.

**Comment by tyler-furby** [comment]
Removed sponsors from post page in a660eba

**Comment by tyler-furby** [comment]
Removed sponsors: a660eba
