### ISSUE TITLE
Remove Right Sidebar with "Related Links" and "Comments" in sideways text from episode page

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#511]

**Comment by dasimandl** [comment]
@crablar @jasonify  Is this still an open issue? Also, can you provide a link to this issue to better understand the problem?

**Comment by alloydsbux** [comment]
@dasimandl here's a screenshot of the sideways text to remove. This is on every podcast episode page.

<img width="1434" alt="screen shot 2018-10-03 at 5 05 59 pm" src="https://user-images.githubusercontent.com/41974312/46446119-46cc8900-c72f-11e8-99f3-d7c81fb41411.png">

**Comment by dasimandl** [comment]
@alloydsbux Thank you for clarifying this issue.  I plan to start development on this over the weekend!

**Comment by dasimandl** [comment]
PR submitted for this issue #561
