### ISSUE TITLE
Apostrophe Problem

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#529]
Episodes with apostrophes not rendering correctly

https://www.softwaredaily.com/forum/5b06a23f01c8780004b9c767

**Comment by rdela** [comment]
So I opened #536 which contains a fix for this along with updating the many vulnerabilities surfacing in `npm audit`. Maybe we want to split that up but I figured if I was going to open a PR might as well try to do those upgrades too while I was at it. Here are some more examples of recent episodes with apostrophes to test against:

- https://www.softwaredaily.com/forum/5b5997116e01fc0004960782 - Ghost: Open Source Publishing Platform with John O’Nolan)

- https://www.softwaredaily.com/forum/5b3f52ecceeaa40004bebbe9 - 
Future Projection with Tim O’Reilly

- https://www.softwaredaily.com/forum/5b4624e06f117300047ca06c - 
Can’t get engineering interviews? Try the side door.


Those are all production links but here are a couple staging ones one could use to try the fix once it is pushed to `develop`:

- https://sedaily-frontend-staging.herokuapp.com/forum/5ada71d756f4742864bf8dd4 - 
Dashboarding and Query Latency with Tom O’Neill

- https://sedaily-frontend-staging.herokuapp.com/forum/5ada71d856f4742864bf8f35 - 
Cloud R&D with Onsi Fakhouri


Last one demonstrates this fixes all unescaping issues like ampersands in addition to apostrophes.

Production version of same:

- https://www.softwaredaily.com/forum/5ade3e719a2f26143f8852b5 - 
Cloud R&D with Onsi Fakhouri


...and a more recent one to grow on:

- https://www.softwaredaily.com/forum/5b0fdcdd4994510004273065 - Life Science R&D with Sherwin Yu

**Comment by rdela** [comment]
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/536#issuecomment-415983760

> @andrewmarklloyd: […] the [review app is live](https://sedaily-frontend-stagin-pr-536.herokuapp.com/)!

So here are a couple review versions of links above with the unescaping fix:

Open Source Publishing Platform with John O’Nolan
https://sedaily-frontend-stagin-pr-536.herokuapp.com/forum/5b5997116e01fc0004960782

Life Science R&D with Sherwin Yu
https://sedaily-frontend-stagin-pr-536.herokuapp.com/forum/5b0fdcdd4994510004273065
