### ISSUE TITLE
upvote/downvote score display is confusing/inconsistent

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#535]
I came across this while trying to finish the manual testing checklist with Cypress e2e tests. I do recall discussing in Slack that the default of 1 score was a bit confusing but let it be as. The problem here is that it is also inconsistent. The displayed score will drop from 1 to -1 when the backend score drops from -1 to -2.

This has to do with the JS expression in `src/components/VotingArrows.vue`: `<div class='score-text'>{{ score + 1 || 1}}</div>`. If score = -1, score + 1 is 0 or falsy so it will display 1. But if it's -1 it's truthy so will display -1. 

Based on how the app is use this is super low priority but I'm going to test the voting different in Cypress until the expected behaviour is clarified. @tyler-furby - What was the original intent around this change?

![downvote-minus-2](https://user-images.githubusercontent.com/10546720/41810934-d2088380-76d4-11e8-8e5f-21038305f0a8.gif)

**Comment by jasonify** [comment]
Feel free to revert the upvote to the old way. I think it caused more problems than it's worth.
