### ISSUE TITLE
Add link to Slack dev channel  to all repos in the Readme files.

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#54]

**Comment by andrewmarklloyd** [comment]
Linking to http://softwaredaily.herokuapp.com/ allows people to get an invite to the SEDaily group. Linking to https://softwaredaily.slack.com/app_redirect?channel=sed_app_development assumes they are already in the group and can link to the channel. Which one is preferable?

**Comment by crablar** [comment]
Latter is fine.
