### ISSUE TITLE
Reusing validation from the server on frontend?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#55]
Would be nice if we could reuse joi and have something like this:

      email: Joi.string().email('Please make sure you provide a valid email').required('Please make sure to provide an email')

**Comment by TheHollidayInn** [comment]
Speaking generally here, we can start to package some of our code from the server and client into modules. As long as we abstract logic like entity validation from the frameworks (Vue and Express) we should have a separate shared repo and import that like any other package.

**Comment by jasonify** [comment]
Worth figuring out what we can refactor into small libraries. For now I am using a vue validation library.

**Comment by TheHollidayInn** [comment]
Yea, if we just follow some of the clean architecture guidelines we could share some code. Right now we don't have too much business logic, but it is a good practice in general.
