### ISSUE TITLE
Incorrect Transcript Link

### ISSUE THREAD

**Issue by hoppy-kamper** [SoftwareEngineeringDaily/sedaily-front-end#559]
The transcript link for episode https://softwareengineeringdaily.com/2018/09/28/prisma-graphql-infrastructure-with-soren-bramer-schmidt/ links to https://softwareengineeringdaily.com/wp-content/uploads/2018/09/SED681-Android-Things.pdf

**Comment by andrewmarklloyd** [comment]
@hoppy-kamper this is actually an issue with softwareengineeringdaily.com and not softwaredaily.com, which is what this repository is for. All podcast data originates with softwareengineeringdaily.com, and we run a scraper to import it into the softwaredaily.com database. Although I'm not sure where the best place for that type of issue is but I'd say this works as well as any place.
