### ISSUE TITLE
Make it a PWA

### ISSUE THREAD

**Issue by AjayPoshak** [SoftwareEngineeringDaily/sedaily-front-end#575]
I am a daily listener of SED. So I would love to have SED as PWA on my phone.  
To become a PWA, as it would need to register a service-worker and add a manifest file.  

If we agree to that, then I would love to do that changes.

**Comment by andrewmarklloyd** [comment]
@AjayPoshak we do have the iOS and Android apps available to download. Is there anything about the app that doesn't fit your needs that a PWA would solve?

**Comment by AjayPoshak** [comment]
I don't like having too many apps on my phone, as it requires space and constant updates even though I'm not using them.  Whereas PWAs on the other hand, occupy less space and doesn't require updates as it downloads its resources on the fly.

I am using your mobile website to listen to awesome podcasts daily during my commute.  There are a few issues around it, as it is a bit slow and doesn't harness the full power of web platform such as registering service worker for better bootup time, background fetch whenever I download a podcast.

One more general issue that I experience is that whenever I close my browser my state(podcast, and my audio position) isn't saved.  So next time, when I open it up, I don't know which podcast I was listening to and where I left it last time.
