### ISSUE TITLE
CSS Issue on desktop view (left margin too small)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#60]
<img width="909" alt="screen shot 2017-10-26 at 10 00 15 am" src="https://user-images.githubusercontent.com/150265/32066419-8719fdc0-ba34-11e7-9e26-4337c9bc600c.png">

**Comment by nhc** [comment]
Can I grab this one?

**Comment by crablar** [comment]
Absolutely!

**Comment by crablar** [comment]
If you need any help fixing or doing the PR process, feel free to ping me or @jasonify in Slack.

**Comment by jasonify** [comment]
:) thanks for looking into it @nhc
