### ISSUE TITLE
Implement Algolia for searching our content

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#604]
Bonus points for indexing transcripts

**Comment by bikingbadger** [comment]
I wouldn't mind giving this a go if it's a good first issue. I'm not exactly sure what the Algolia service is but sure a bit of reading and I should manage. My first question is whether this is implemented through the backend somehow or do should the front end communicate directly with Algolia?

**Comment by crablar** [comment]
Hi @bikingbadger , I don't think this is a good first issue after all. It has some complexities to it.

**Comment by crablar** [comment]
Some issues with search:

- [ ] search "Kubernetes". Click on top result. It loads. Then search "Kubernetes" again and click on a different result and it loads a blank page that just says "Related Links" on it

- [ ] search bar should just say "Search" instead of "Search for a product"

- [ ] if user just types in a keyword such as "Kubernetes" and presses enter, results should be listed; they results list can be at a url of /search&query={query}

**Comment by crablar** [comment]
Looking good. 

One fix:
1. search for "Kubernetes", click an item and it navigates to that post page
2. search "React" and press enter, it does not go to the "React" search page

One improvement:
- search should return the filtered results ordered by number of Likes

**Comment by sterlingrules** [comment]
The first fix is straight forward. But just so you're aware, the one improvement is a larger project since I'll have to first reindex all projects with their like counts and then reindex them as their like counts change. Not a problem, but just letting you know. I'll jump on these soon.

**Comment by crablar** [comment]
The improvement can be ignored. I'll make it an issue.

**Comment by sterlingrules** [comment]
Alright, these changes minus the improvement have been deployed. The url now changes with search results as well.
