### ISSUE TITLE
Additional Frontend Design Changes

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#624]
- [x] Add heart and bookmark buttons to posts in feed; give a | separator after date and have the heart empty with number of votes that have been made
- [x] Make a similar change to the post, on the same line as the comments and date
- [x] Search should return the filtered results ordered by number of Likes

**Comment by sterlingrules** [comment]
@crablar what do you mean by likes? I don't see anything referencing a "Like", do you mean votes? If you mean votes, I don't see a voting mechanism related to the posts, only on the comments.

**Comment by crablar** [comment]
@sterlingrules Indeed. I just realized that the episode Likes was removed from the frontend interface. It exists in the mobile apps (for reference download the app), so I assume it also exists in the backend data model--and I think it is a good feature.

**Comment by sterlingrules** [comment]
@crablar Like and Bookmarking are now in staging. Let me know if they're good to ship!

**Comment by crablar** [comment]
@sterlingrules I'm not seeing it, is it in a different environment than https://sedaily-frontend-staging.herokuapp.com/ ?

**Comment by sterlingrules** [comment]
@crablar no, it looks like Marcos had deployed a different branch over it. I just redeployed, so the like/bookmark features should be in staging now - https://sedaily-frontend-staging.herokuapp.com/

**Comment by crablar** [comment]
@sterlingrules can you make both icons bigger? See Twitter, or the SED mobile app for a reference.

Also, the bookmark does not need to show the number of bookmarks. It should just show whether or not the user has bookmarked it.

After those changes, good to ship!
