### ISSUE TITLE
Post Layout Changes

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#630]
desktop
- [x] [model the left and right parts of the page like Quora](https://www.quora.com/What-are-some-lesser-known-facts-about-Eminem), where the main post material is on the left and related materials and comments are on the right
- [x] down the left part of the page it should be the header, the post description, and then the transcript; there should be a subset of the transcript (~3 paragraphs) that is revealed by default and a button that says "Read all" that expands the rest of the transcript (the transcripts are quite long); if there is no transcript don't render this part
- [x] three separate component types are down the right side of the page: related episodes, related links, and comment threads
- [x] related episodes works the same way as related links, except it has to be a link that is prefixed with softwaredaily in the link, and then it generates a square episode module like the ones on the post Sketch, except down the right of the page instead of on the bottom
- [x] related links should be just below it
- [x] highlighting a part of a post should allow you to Tweet it or comment; replace the pencil icon with the tweet
- [x] the comment interface should work as in the design; every highlight should create a new thread; threads can have comments and responses around them that are displayed on the page as in the design
- [x] if a comment module would conflict with a related link or related episode module, keep the comment module in the correct place and move the related link or related episode module above/below it
- [x] there is also the ability to just create a response at the bottom of the post between the transcript module and the subscription module; this is a single thread that is a general response to the episode
- [x]  /forum is not a place that should be reached by any of these flows; consider it deprecated
- [x] share to Twitter should render the featured image of the post within the tweet

- [x] remove the "X comments"  that says how many threads there are on the right hand side ([2 in this example](https://sedaily-frontend-staging.herokuapp.com/post/5e4765ee857231000c7380ef/Data-Warehouse-ETL-with-Matthew-Scullion))
- [x] each highlight thread should be separated by some whitespace, rather than all being part of the same contiguous grey box
- [x] each highlight thread should have a "Reply/Delete/Edit" part that is always visible, rather than onHover

mobile
- [x]  the header module is at the top, followed by the description module, then the transcript module, then related episodes, then related links, then each of the comment threads

**Comment by crablar** [comment]
@sterlingrules it is a lot of related stuff, so I threw it all in a single issue.

**Comment by sterlingrules** [comment]
> related episodes works the same way as related links, except it has to be a link that is prefixed with softwaredaily in the link, and then it generates a square episode module like the ones on the post Sketch, except down the right of the page instead of on the bottom

I'm not completely sure how related links work currently. They're not shown in the Sketch designs. Is the way related episodes are currently working in staging correct? Should I display the related links similarly to that? Each link being its own block? Or all of them grouped together like Popular Stories?

**Comment by crablar** [comment]
@sterlingrules related links should work [how they work in current production version](https://www.softwaredaily.com/post/5e300b10d5d1db000c998e64/Replicated-Software-Delivery-with-Grant-Miller-and-Marc-Campbell). They were left out of the sketch design. They can just be barebones links without fancy design, ordered sequentially down the right side with the ability for people to add more links easily.

With related episodes, use a square module similar to the designs, but down the right side of the page.

**Comment by sterlingrules** [comment]
@crablar 

>the comment interface should work as in the design; every highlight should create a new thread; threads can have comments and responses around them that are displayed on the page as in the design

Currently, when you highlight some content and click the comment icon it opens a "New Forum Post"  view at the path /new-thread. Is this part of the forum that you'd like to deprecate? If you'd like highlighting to create a new comment, I am unclear about the UI for this. The designs show how it ends up, but does not offer the process in which it gets there. Should the highlighted copy simply populate the comment box? Should the highlighted copy then also remain highlighted for other users, similar to Medium? If so, does clicking the highlighted copy for other users offer some additional functionality?

How similar is this feature to Medium because this feature on Medium is very robust.

**Comment by sterlingrules** [comment]
@crablar 

>there is also the ability to just create a response at the bottom of the post between the transcript module and the subscription module; this is a single thread that is a general response to the episode

What is the difference between a response and a comment? Do these live in separate places? In production, I only see a comment section.

**Comment by crablar** [comment]
There is one default general discussion thread at the bottom, then there are the user generated threads from the highlights on the right hand side.

Every time a user makes a highlight, a new "highlight thread box" is created on the right. The highlight thread box associated with that highlight should be parallel with the highlight on the right side. The user interface for creating a new "highlight thread box" should be similar to what you have in staging right now, except it should include the highlight in a [special box](https://medium.com/@natanbaredes/how-is-this-possible-645d233bd500) similar to how Medium displays highlights.

It should be possible to create two overlapping threads. Rules can be pretty simple--if a piece of text has been highlighted one or more times by a user, that text appears highlighted within the post.

**Comment by crablar** [comment]
@sterlingrules added a checkbox around Twitter sharing

**Comment by crablar** [comment]
@sterlingrules added an issue about sharing on Twitter, the image renders on Slack but does not render in Twitter

**Comment by sterlingrules** [comment]
> @sterlingrules added an issue about sharing on Twitter, the image renders on Slack but does not render in Twitter

Are you using prerender.io? If so, could I get access so I can try and see why the OG tags aren't rendering?

**Comment by crablar** [comment]
@sterlingrules added some changes to the comment/highlighting design

**Comment by crablar** [comment]
@sterlingrules Looking good, some fixes:

- [ ] After a highlight has been placed over text, clicking on the text should still display the little black icon that lets you tweet or comment. Then if the user clicks comment, it renders the option to comment
- [ ] When you tweet a highlight, the highlighted content should appear in the tweet draft in front of the page link and @software_daily
- [ ] Related episodes should be blank by default, and should have the "+ Add New Episode" feature that is similar to the related links feature
