### ISSUE TITLE
Create notification system

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#633]
- [x] add a bell icon in the upper section, to the right of subscribe; bell displays the number of unread notifications you have; clicking it displays those notifications and marks them as read

- [x] when a user Likes an episode or adds a comment, the user becomes subscribed to the comments on the episode

- [x] if a user makes a comment, other users that are subscribed to the comments on the episode get a notification

**Comment by marcosschlup** [comment]
@crablar Do you believe that we need to send push notifications on iOS and Android apps? If so, we use a service (I think a paid one) like Firebase. If not, I do it in our structure (it’s not difficult)

**Comment by crablar** [comment]
@marcosschlup we will need to do this eventually. Focus on the web use case, and architect it to be easily consumed by mobile if possible.
