### ISSUE TITLE
Implement Private Ad-free RSS Feed

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#635]
This should be done after #636 

- [x] the mp3 to use should be the ad-free episode that subscribers have access to through softwaredaily.com

- [x] every subscribed user gets a unique RSS feed URL; if their subscription runs out, this URL should be 404'd

**Comment by crablar** [comment]
@marcosschlup please make changes to the /subscribe page: 
- change "You are subscribed :)" to "You are subscribed. Thank you."
- below that, people who are subscribed should see the link to the ad-free feed and it says: "Enjoy your ad-free episodes! {link}

Subscribe to this private RSS feed on a podcast player such as Podcast Addict (Android) or Overcast (iOS)"

**Comment by marcosschlup** [comment]
One it!
- [ ] change "You are subscribed :)" to "You are subscribed. Thank you."

**Comment by marcosschlup** [comment]
Done in https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/642

**Comment by marcosschlup** [comment]
- [ ] below that, people who are subscribed should see the link to the ad-free feed and it says: "Enjoy your ad-free episodes! {link}

**Comment by marcosschlup** [comment]
<img width="609" alt="Captura de Tela 2020-02-19 às 14 57 27" src="https://user-images.githubusercontent.com/8609590/74860814-0e2f4e80-5328-11ea-8596-02f12b0677f1.png">

@crablar

**Comment by crablar** [comment]
@marcosschlup  looks great!

**Comment by marcosschlup** [comment]
@crablar please let me know when you get that new image / logo for the podcast

**Comment by crablar** [comment]
![Software Daily Logo 3kx3k](https://user-images.githubusercontent.com/1283090/74965158-8d289380-53c9-11ea-95ba-e4fe96b77f75.png)
@marcosschlup here you go. Please use this for both RSS feeds.

**Comment by marcosschlup** [comment]
@crablar Is there a CDN for those things? I see a AWS link in some places

**Comment by crablar** [comment]
you can just stick it on a URL somewhere on the site. I think it gets cached by Apple Podcasts infrastructure

**Comment by marcosschlup** [comment]
Nice, I'll use the frontend assets folder then
