### ISSUE TITLE
package.json madness

### ISSUE THREAD

**Issue by sw-yx** [SoftwareEngineeringDaily/sedaily-front-end#64]
what on earth happened here?  can we clean up the packagejson or is this necessary?

![image](https://user-images.githubusercontent.com/6764957/32084671-8655e0de-ba98-11e7-9ac0-7e0c70a6fcca.png)

**Comment by jasonify** [comment]
wow, haven't seen this. will need to investigate

**Comment by sw-yx** [comment]
these are not tests, these are straight up `npm install` output

i mean just look at your package json right now. [dependencies](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/package.json#L20) vs [devdependencies](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/package.json#L97) was that somehow autogenerated and something went wild?

**Comment by jasonify** [comment]
Ahh yeah, a lot of stuff should be only be in dev but seems to be in both.


Just wondering what version of node + npm you are running?

> 
> $ npm install
> npm WARN deprecated yarn@0.23.4: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install

[npm install output ](https://pastebin.com/cuawCv83
)

```
node -v
v7.10.1
```

```
 npm -v
4.2.0
```

**Comment by sw-yx** [comment]
node 8.5 npm 5.3

**Comment by jasonify** [comment]
Okay thanks, will see if that makes a difference.

**Comment by joshmorel** [comment]
This seems to be caused by vue-cli scaffolding as I've encountered it before in sample projects. I really don't know why... but yeah most should just be in devDependencies.

**Comment by TheHollidayInn** [comment]
The issue comes from trying to deploy on Heroku which doesn't support static sites well. I should have clean it up though.

**Comment by sw-yx** [comment]
ah. heroku doesnt support devdependencies. what you do is build first and then only deliver the bundle on heroku. since this is a static site can also consider moving to firebase or netlify

**Comment by TheHollidayInn** [comment]
Yep! I want to move to netlify

**Comment by joshmorel** [comment]
As this is front-end what about storage on S3, Digital Ocean Spaces, or similar. Cloud Flare (SED spnsor!... I think) could provide the CDN. Or will netlify provide all that?

**Comment by TheHollidayInn** [comment]
Netlify can provide that but what are you suggesting we use those for? We are talking about profile images on S3, but that is currently an API issue. We don’t have many assets in the front end atm

**Comment by sw-yx** [comment]
netlify is freeeeeeeee

**Comment by sw-yx** [comment]
lol and 2 years later i work at netlify...
