### ISSUE TITLE
More design improvements

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#640]
Post page
- [x] Topic labels should be gray with gray text (like Quora) https://www.quora.com/What-are-some-lesser-known-facts-about-Eminem
- [x] Related links should only require you to drop in the link, rather than requiring you to also enter in a description; we should grab the title of the link and shorten it with a "..." suffix, and grab the favicon of that link to display it to the left of that link
- [x] Do the same for related episodes
- [x] remove the text "About the episode"
- [x] remove "Subscribe: Apple | Android | RSS"
- [x] remove caret from blank comments section at bottom
- [x] change "Sponsors and Links" to just "Sponsors"
- [x] change "view discussion" to "View Transcript"

On the /subscribe page:

- [x] under the big heading text that says "Subscribe": "Listen to Software Daily on Apple | Android | RSS"
- [x] change "Get ad-free episodes" to "Become a paid subscriber and get ad-free episodes"
- [x] change "2.5 years" to "4.5 years"
- [x] add hyphen to make it "How do I listen to ad-free episodes?" and underneath that, add "After becoming a paid subscriber, you can listen to ad-free content in two ways. You can listen in the SEDaily app for iOS or Android. Also, you will get a link to a private RSS feed that has no ads. You can subscribe to the paid content on a podcast player."
- [x] remove the section that says "I thought there was premium content...jeff@softwaredaily"
- [x] remove the Patreon section too

**Comment by sterlingrules** [comment]
@crablar 

> under the big heading text that says "Subscribe": "Listen to Software Daily on Apple | Android | RSS"

I'm a little unclear about this task. Am I changing "Subscribe" to "Listen to Software Daily on Apple | Android | RSS" ?

**Comment by crablar** [comment]
@sterlingrules some additional changes:
/post page
- [ ] make the related episodes only allow links with "softwaredaily" in the title
- [ ] the related link and episode boxes should only be the height of a single line of text, they shouldn't be a taller expandable text box
- [ ] remove the "Submit" button, a user should be able to drop in the link and hit enter
- [ ] URL validation should be weaker, don't require http, https, or www; just require a string of text, followed by a "." and a non-space string immediately after that, as well as no spaces in the entire string
- [ ] make both related links and related episodes have smaller height, with the links closer together; if there are zero related links and episodes, the boxes should be pretty short

**Comment by sterlingrules** [comment]
@crablar 

>put grey line as an outline around each post on the main feed page so it is easier to scroll

I am unclear about this task. Each post is in a gray box, so I am not sure where to put this grey line.

>the related link and episode boxes should only be the height of a single line of text, they shouldn't be a taller expandable text box

I'm not sure I understand this task. I removed the collapsable input and made it static. Let me know if that is not what you meant.

**Comment by crablar** [comment]
@sterlingrules notice how some items in the feed (such as Courier with Troy Goode) have a white featured image, which throws off the feed presentation. I'm imagining a grey line that extends to this top portion.

For the input boxes, notice how if you click "Add Related Link" it reveals a box that is tall and bulkier than the height of a single line of text. The box should be less high.

**Comment by sterlingrules** [comment]
@crablar the latest changes are up in staging: https://sedaily-frontend-staging.herokuapp.com/

**Comment by crablar** [comment]
@sterlingrules having trouble adding a related episode. This field should do similar validation as related link, but should verify that softwaredaily is in the string.

**Comment by sterlingrules** [comment]
>make the related episodes only allow links with "softwaredaily" in the title

@crablar I am also verifying if `softwaredaily` is in the finally parsed title. It was initially set up to verify in the URL, but should it _only_ check in the URL?

**Comment by crablar** [comment]
@sterlingrules I think we clarified this on Slack, sorry to miss this.

**Comment by sterlingrules** [comment]
@crablar we did, no worries. This issue should be resolved now.

**Comment by crablar** [comment]
@sterlingrules yes, good to merge.
