### ISSUE TITLE
Topic Pages

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#643]
Designs are here: https://www.figma.com/file/x3V9hZWav7veZeI2aHKkev/Topic-Pages-Design?node-id=0%3A1

A topic page is a condensed, canonical source of information about a technical topic, maintained by a student of the field.

A topic page is limited to 3 pages and 3 images. In addition, the page contains related episodes, related links, and related topics.

The topic page maintainer is featured prominently on the page.

Topics include:
Kubernetes
Service Mesh
Bitcoin
React
GraphQL
JAM Stack
No Code
Kafka
Spark
Flutter
Machine Learning
Netflix Engineering

Users can highlight sections of the topic page to make suggestions for it.

**Comment by crablar** [comment]
Here is a first draft of a topic page from one of our authors, to give a sense of what the raw content is. https://docs.google.com/document/d/11n391hzrSTPyHP8BUDt1L6A8MT6TSlZ58jnxcRe7uKE/edit?usp=sharing

**Comment by marcosschlup** [comment]
@crablar How we navigate to a topic from the home page?
today, `/topics/kubernetes` leads to a filtered list os posts. This is going to chance?

**Comment by crablar** [comment]
Good question.

If a topic has not been defined in the /admin page, then the experience is the same as it is today.

If the topic has been defined in the admin page, it changes to the format that is seen in Figma.

**Comment by marcosschlup** [comment]
@crablar 

1. The `related episodes` in a topic will be automatic? Or someone needs to add, like in the post today
2. How can the maintainer get to the Topic edition for the first time? Do we show it somewhere? Profile? Anyway, there is a route now.
3. The list of topics on Home is not complete. Should we create a navigation option to discover all the Topics that have a Topic Page?

**Comment by marcosschlup** [comment]
@crablar I believe that the mobile app may be using the same / topics route to list the posts. If we change, it can affect the APP, right?

**Comment by marcosschlup** [comment]
Well, I'll change the route to `/topic/kubernetes`, and not `/topicS/kubernetes` like today

**Comment by crablar** [comment]
> The related episodes in a topic will be automatic? Or someone needs to add, like in the post today <
Someone needs to add them (for now at least)

> How can the maintainer get to the Topic edition for the first time? Do we show it somewhere? Profile? Anyway, there is a route now. <
Once admin (me) creates a topic for the first time, it creates a blank topic page, and should send an email notification to the topic maintainer.

> The list of topics on Home is not complete. Should we create a navigation option to discover all the Topics that have a Topic Page? <
Yes, I'll make an issue.

**Comment by crablar** [comment]
@marcosschlup a few changes to make:

- [ ] clicking on a topic ([ie "Clojure" in this post](https://www.softwaredaily.com/post/5e79d0ea58609a000c1a16bb/Datomic-Architecture-with-Marshall-Thompson)) should route to /topic/<topic name> if that topic page has been created and published
- [ ] if no maintainer has been assigned to that topic or a maintainer has been assigned but not published it, then the page should display the same as it would today with /posts/<topic name>--a list of all the past episodes
- [ ] if a maintainer has been assigned to that topic and published it, then the page should should look like a published topic page; all of the episodes that would be listed under /posts should be automatically added to the "Related Episodes" list (ie, if there was a published topic page about Kubernetes, the "Related Episodes" list should have all the related episodes
- [ ] remove the "Related Links" section from Topic pages

**Comment by marcosschlup** [comment]
@crablar About inactive status on topics. Just notice that, if a topic is inactive, it doesn't show in the home list, like in `Most Popular`.
Is that good behavior? I find it interesting to have something to indicate whether the topicPage should be shown or not. Something to leave it out (redirecting to posts) if the maintainer is still editing. I had initially thought of this status.
If we leave it like this, topicPage is not accessible while editing (leaving it inactive) but it also does not appear in the list. We can leave it appearing normally in the list, but redirecting. If the behavior of the list is desirable, we can create another mechanic, such as a new field.

**Comment by marcosschlup** [comment]
I'll look into that `Publish` behavior

**Comment by crablar** [comment]
> @crablar About inactive status on topics. Just notice that, if a topic is inactive, it doesn't show in the home list, like in Most Popular.
> Is that good behavior? I find it interesting to have something to indicate whether the topicPage should be shown or not. Something to leave it out (redirecting to posts) if the maintainer is still editing. I had initially thought of this status.
> If we leave it like this, topicPage is not accessible while editing (leaving it inactive) but it also does not appear in the list. We can leave it appearing normally in the list, but redirecting. If the behavior of the list is desirable, we can create another mechanic, such as a new field.

This is all good.

> I'll look into that Publish behavior. Create a publish status in the edit page so that the maintainer can control if it is published or not. I think it is more the behavior that you said

This is a good idea. There should be a "Save" and a "Publish/Unpublish".

Also, the episodes that are tagged with this topic should be automatically added to Related Episodes.

**Comment by marcosschlup** [comment]
@crablar All the episodes? With pagination? Or just X top ones?

**Comment by crablar** [comment]
It's a good point that this could be very long in the case of some topics like Kubernetes.

Just grab the top 10 by number of likes and add them to the related episodes. That will be a quick fix that will allow us to have some related content inserted automatically.

**Comment by marcosschlup** [comment]
Yeah, that won't take long. I'll put a "See all" above the top 10, leading to topic posts

**Comment by marcosschlup** [comment]
@crablar The change item: "clicking on a topic (ie "Clojure" in this post) should route to /topic/ if that topic page has been created and published" already works. Didn't that work for you?

**Comment by crablar** [comment]
You are right, that does work :)

**Comment by crablar** [comment]
A few other design changes:
- remove the long gray bar that says "0 Comments" (don't need to list the number of comments there)
- if a topic maintainer is looking at a topic page, they should see an "Edit" button under the title of the page
