### ISSUE TITLE
Profile improvements

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#645]
- [x] every user's profile page should be public with a link that is something like /profile/{firstname-lastname-a452jfks}
- [x] remove the "My Topics" section
- [x] a user's profile page should list a feed of their recent activity including the following elements: liking an episode, commenting, highlighting, adding a related link, adding a related episode

**Comment by marcosschlup** [comment]
@crablar I think it would be interesting to put `(public)` in the profile fields that will be visible on the public profile page

**Comment by crablar** [comment]
@marcosschlup great point.

Another thing I just realized: what is the purpose of the "Username" field in profile? I'm not sure if this is something that was deprecated. Is it referenced anywhere?

**Comment by marcosschlup** [comment]
@crablar  I found a lot of username reference. Used even in login and events.

A personal opinion. I find username an interesting option to avoid having to expose the name in some situations, such as mentions.
