### ISSUE TITLE
Episodes without transcripts

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#650]
@sterlingrules do you know why [this](https://www.softwaredaily.com/post/5d2c455ca04c8a000c9b35ee/Facebook-PHP-with-Keith-Adams) episode doesn't have an embedded transcript?

The corresponding SED post is [here](https://softwareengineeringdaily.com/2019/07/15/facebook-php-with-keith-adams/).

**Comment by sterlingrules** [comment]
I think it might just be timing out. That corresponding link is not working for me right now, and I was having timeout issues when running the miner earlier today.
