### ISSUE TITLE
Remove "Announcements" and "Sponsorship inquiries" from Software Daily posts

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#651]
Might not be possible to clean all of these up, but it would be nice to get some regex matching to remove these from the posts and put it in the SEDaily miner

Example: https://www.softwaredaily.com/post/5d68ea6670a7d4000c047cee/Facebook-Parse-Acquisition-Part-2-with-Ilya-Sukhar

**Comment by sterlingrules** [comment]
@crablar I wrote a script in the `sedaily-miner` that handles this. But since it's stripping text, I just want to make sure — when Announcements and Sponsorship inquiries are included, is the general format always the same and at the bottom of the post?

**Comment by crablar** [comment]
@sterlingrules Almost always, yes. There might be some edge cases from old episodes, but that's not a big deal.
