### ISSUE TITLE
Can't Make iTunes Podcast Submission 

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#657]
Looks like we need an Explicit tag: "Can’t submit your feed. There is no explicit tag in your feed, or the explicit tag is empty." (we are not explicit)

https://help.podbean.com/support/solutions/articles/25000017026-when-your-podcast-is-rejected-from-apple-podcasts-itunes-

After submitting https://software-enginnering-daily-api.herokuapp.com/api/rss/public/all

**Comment by marcosschlup** [comment]
@crablar can you test again, please? Just updated

**Comment by crablar** [comment]
Got these errors now:
- [ ]  Can’t download episodes from your feed.
- [ ]  Podcast artwork must be between 1400 x 1400 and 3000 x 3000 pixels, JPG or PNG, in RGB color space, and hosted on a server that allows HTTP head requests.
- [ ]  Can’t submit your feed. There is no category tag in your feed, or the category tag is empty.
- [ ]  Can’t submit your feed. There is no explicit tag in your feed, or the explicit tag is empty.

**Comment by marcosschlup** [comment]
Weird, explicit again

**Comment by marcosschlup** [comment]
I had validated with those sites that you had sent me. It was all right.
About the image, do you have any in the necessary format?

**Comment by marcosschlup** [comment]
https://podba.se/validate/?url=https://sedaily-backend-staging.herokuapp.com/api/rss/public/all
This is the test. Category should be correct. I'm investigating

**Comment by marcosschlup** [comment]
this is a more complete one: https://castfeedvalidator.com/?url=https://sedaily-backend-staging.herokuapp.com/api/rss/public/all

It alerts to a maximum of 300 episodes

**Comment by marcosschlup** [comment]
@crablar Can you test with temp https://sedaily-backend-staging-pr-321.herokuapp.com/api/rss/public/all ?

**Comment by crablar** [comment]
"Can’t submit your feed. There is no explicit tag in your feed, or the explicit tag is empty."

**Comment by marcosschlup** [comment]
@crablar sorry! I have send the wrong one.

https://sedaily-backend-staging-pr-323.herokuapp.com/api/rss/public/all

**Comment by crablar** [comment]
@marcosschlup it's good to go! Let me know when it's in production.

**Comment by marcosschlup** [comment]
@crablar what about the image? I didn't change it

**Comment by marcosschlup** [comment]
@crablar it's in production now

**Comment by crablar** [comment]
@marcosschlup it works! Submitted to iTunes.
