### ISSUE TITLE
Put highlight threads in a lightbox

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#669]
The highlight threads are cramped on the side, and the UX on mobile doesn't work. Bad design decision by me.

When user highlights or clicks on an existing highlight, it should reveal the option to tweet or comment the same way it does now; if they click the little comment icon, it should open a lightbox that takes up most of the screen; the lightbox should be a bigger experience of the comment threading that is currently off to the right side. This should also work on mobile.

Also, the highlights appear on the right side of the page without the comments below them, and clicking on one of them opens the lightbox discussion.

**Comment by crablar** [comment]
@sterlingrules @marcosschlup what do you think of this concept?

**Comment by marcosschlup** [comment]
@crablar  I find it interesting in some way to keep some kind of accountant on the post page. something that indicates that there are X comments for a highlight. But I'm not sure of the ideal scenario

**Comment by crablar** [comment]
Agreed. Also, the highlights appear on the right side of the page, and clicking on one of them opens the lightbox discussion.

**Comment by sterlingrules** [comment]
Yea, I think it's an interesting and viable solution for mobile.

**Comment by crablar** [comment]
@sterlingrules first draft looking good. Some adjustments:
- [ ] each highlight should appear on the right without any comments beneath it; so the right should just list the highlights vertically
- [ ] clicking on any individual highlight should bring up a dedicated lightbox area for that comment; this is instead of the current implementation where there is a single lightbox with multiple highlights that you can scroll to
