### ISSUE TITLE
Public RSS Issues

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#673]
- RSS feed is not updated as fast as the feed on Software Daily; I'm checking at 10am PST and there is a lag with the RSS feed not having today's episode
- the podcast is not publishing correctly to iTunes; hard to troubleshoot why this is happening

- [ ] generate a new RSS feed from SoftwareDaily every morning after the new episode has been added
- [ ] cache that feed in our CDN (I think this can be done with Prerender)

**Comment by crablar** [comment]
@marcosschlup  this can wait until after Topic pages are done

**Comment by marcosschlup** [comment]
@crablar 
The update happens in a "conjob" inside API. We just need to set a proper time (or times)
The RSS is cached in memory inside API. Are you seeing any impact related to cache?

**Comment by crablar** [comment]
The cronjob should run after the cronjob that generates the Software Daily feed.

Not sure what is causing the failure on iTunes. I got an email that said the podcast should be available here: https://podcasts.apple.com/us/podcast/software-daily/id1501466970

**Comment by marcosschlup** [comment]
I read in one of the tests that iTunes was able to accept up to a maximum of 300 episodes. Have we reached any limits?

**Comment by crablar** [comment]
I think that is the problem. Let's try limiting it to 300 episodes.

**Comment by marcosschlup** [comment]
Right. Will do that

**Comment by marcosschlup** [comment]
@crablar Just limited the RSS to 300 and updated the cronjob. Can you test in iTunes?

**Comment by crablar** [comment]
Testing it. Strange--iTunes accepts the feed but does not list it. I contacted support and will let you know.

**Comment by marcosschlup** [comment]
@crablar 
Any news on this subject?
Is the cronjob better now?

**Comment by crablar** [comment]
@marcosschlup Try to fix these issues with the formatting: https://castfeedvalidator.com/?url=https://software-enginnering-daily-api.herokuapp.com/api/rss/public/all

**Comment by crablar** [comment]
@marcosschlup response from Apple: I see all of your episodes are missing valid enclosure tags, and you've only included closing enclosure tags. https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Sorry to ask you to jump back and forth between projects. Once we get this issue wrapped up we'll stop the context switching.

**Comment by marcosschlup** [comment]
@crablar 
I found the problem. I was being deceived.
I encountered a problem that caused RSS to generate correctly only the first time. Then, in cronJob, it got empty tags.

I already made the correction

**Comment by crablar** [comment]
@marcosschlup we are live! Nice work: https://podcasts.apple.com/us/podcast/software-daily/id1501466970
