### ISSUE TITLE
Add badge system

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#676]
Relying on your design skills for this. A user's profile should display their progress towards:
- [x] adding 5 related episodes (if they have all 5 they get a Episode Curator badge)
- [x] add 5 highlights to your favorite episodes (if they have all 5 they get a Commenter badge)
- [x] writing a topic page (a user's profile should display a link to each of the topic pages that user maintains)

The badges can live in a similar place to [credentials on Quora](https://www.quora.com/profile/Denis-Oakley).

**Comment by crablar** [comment]
NVM this is a bad idea

**Comment by crablar** [comment]
@sterlingrules how long would you estimate this to take? Marcos has a bit more time with topic pages and I do think this would be a cool feature to launch with.

**Comment by sterlingrules** [comment]
@crablar At least a few days, maybe a week. After I finish #689 I can start working on this one.

**Comment by crablar** [comment]
@sterlingrules Let's start with just adding the purely cosmetic badges for adding related episodes, highlights, and topic pages. 

Then we can have the option to add actual subscription functionality later if we get to it.

**Comment by crablar** [comment]
@sterlingrules updated the issue for this to give a little more description

**Comment by crablar** [comment]
@sterlingrules 
- [ ] make the badges display vertically on the right side of the page (or vertically on mobile); a scroll bar shouldn't display
- [ ] hovering over an uncompleted badge should give a tooltip for what the user needs to do to complete it: "Add related episodes to episode pages", "Highlight interesting parts of an episode", "Write a topic page summarizing a topic"

**Comment by sterlingrules** [comment]
@crablar pushed these changes to staging for review

**Comment by crablar** [comment]
Looks good to go.
