### ISSUE TITLE
Improve transactional email messages

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#680]
- [x] They should be "From" Software Daily
- [x] Title should say "New comment on <the title of the post>"
- [x]  Email should include the entire comment (it's OK to leave out the highlight)

**Comment by sterlingrules** [comment]
I've gone ahead and made these changes, but judging from the implementation I don't know if these emails go out anymore. They seem connected to the deprecated Forum feature.
