### ISSUE TITLE
Likes appear to have disappeared from production

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#681]
https://www.softwaredaily.com/post/5913c07a4ee01db33cacce94/Data-Intensive-Applications-with-Martin-Kleppmann

**Comment by sterlingrules** [comment]
@crablar I think I might not have fully understood this feature. Are "likes" suppose to sync with the count in the Mobile app?

**Comment by sterlingrules** [comment]
Fixed in PR https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/683
