### ISSUE TITLE
Changes to homepage

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#684]
- [x] - move app store buttons to Subscribe page under Checkout the latest episodes
- [x] - remove GitHub button
- [x] - remove the heading "Most Popular"
- [x] - add a button for "Most Popular" that links to /popular that lists the episodes by most likes
- [x] - remove "All"
- [ ] - above the 10 tags on the left side, add any topic pages that have been sent to a maintainer, and the maintainer has actually published them

**Comment by crablar** [comment]
Assigning this to @sterlingrules , and @marcosschlup can do the last checkbox after we get topic pages shipped

**Comment by sterlingrules** [comment]
@crablar 
>add a button for "Most Popular" that links to /popular that lists the episodes by most likes

Where should this button go? Should I make it a link similar to the "All" link?

**Comment by crablar** [comment]
@sterlingrules Correct, just a link.

**Comment by marcosschlup** [comment]
@sterlingrules I just changed the homepage. Could you take a look at whether your changes will actually work in the new structure? Unfortunately, I believe the place is different now. You can take a look at my topics branch

**Comment by sterlingrules** [comment]
@marcosschlup I don't believe my changes have been too severe yet. Any major changes are in a new component and I should be able to merge with minimal conflicts. Is your topics branch good to merge?

**Comment by marcosschlup** [comment]
Almost good to merge. I'm afraid I have changed the home files. That's what I'm afraid of

**Comment by sterlingrules** [comment]
> Almost good to merge. I'm afraid I have changed the home files. That's what I'm afraid of

Yes, I'm aware of the files you've changed, but I think the change is for the best and I can manage the consequences in regards to this page.

**Comment by sterlingrules** [comment]
@marcosschlup When you have a moment, would you mind taking care of the last task on this list?
>above the 10 tags on the left side, add any topic pages that have been sent to a maintainer, and the maintainer has actually published them

I've created a branch at PR #695 that you can use

**Comment by sterlingrules** [comment]
> @marcosschlup When you have a moment, would you mind taking care of the last task on this list?
> 
> > above the 10 tags on the left side, add any topic pages that have been sent to a maintainer, and the maintainer has actually published them
> 
> I've created a branch at PR #695 that you can use

Nevermind, I'll jump on this issue.

**Comment by marcosschlup** [comment]
Hey @sterlingrules , sorry for the delay.
I can look into it, sure

**Comment by sterlingrules** [comment]
@marcosschlup if you have the bandwidth, that'd be great, otherwise, let me know and I'll wrap it up today.

**Comment by marcosschlup** [comment]
@crablar I don't know if I understand the last request.
We have a list of the Most Popular, which will turn into a button.
What would these 10 Tags be?
Can you get a written example of what the entire left menu should look like?

**Comment by crablar** [comment]
The current list of topics are not necessarily "Popular" ones, it is just a statically generated list of topics. The 10 tags can stay there, at the bottom. The full list I envision is:

Most Popular (link to the episodes sorted by most likes)
<Each of the maintainer topics that have been published by the maintainers>
Kubernetes
JavaScript
etc... (but if any of these pages have a published topic page written about them, they should not be displayed)

**Comment by marcosschlup** [comment]
@crablar We'll list all topic pages (published)? Or a top X?

**Comment by crablar** [comment]
You can list the top 30, with most recently published/updated at the top.
