### ISSUE TITLE
On desktop, change episode pages to show the right sidebar even when the page is more narrow

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#685]
Refer to Facebook.com layout, and how they make the page horizontally scrollable to indicate that the right hand column is there

**Comment by sterlingrules** [comment]
@crablar Facebook handles this by having two versions of their website — a mobile and a desktop version. The right sidebar is always shown if you're on a desktop, but goes to a mobile-friendly version if you're viewing from a mobile device. Let me know if you do not want to follow this same pattern and ALWAYS want the right sidebar shown.
