### ISSUE TITLE
Remove sponsor messages from transcripts

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#689]
Cut the blocks of text from [SPONSOR MESSAGE] to INTERVIEW CONTINUED. This will need to be a batch job across old episodes, and a job to run going forward

**Comment by crablar** [comment]
This should be in a cron job that applies it to new episodes which get posted.

**Comment by sterlingrules** [comment]
This currently is part of the cronjob that parses transcripts. Do you have an example of where this isn't being applied so I can see what's happening?

**Comment by crablar** [comment]
https://www.softwaredaily.com/post/5e79d0ea58609a000c1a16bb/Datomic-Architecture-with-Marshall-Thompson

**Comment by sterlingrules** [comment]
This should be resolved by PR - https://github.com/SoftwareEngineeringDaily/sedaily-miner/pull/58
