### ISSUE TITLE
"No Auth - Auth"  -- aka logged out experience should allow you to do a lot

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#69]
In an ideal world, you could do things like "favorite/bookmark" episodes, write notes, etc and have everything be ported to your actual user profile once you do register. 

We would probably store this data on localstorage, can even sync with server and generate recommendations for feed etc.

**Comment by crablar** [comment]
This would be appreciated by a lot of programmer-types.

**Comment by TheHollidayInn** [comment]
So you mean, add offline mode? Should be pretty straight forward, but I don't see a common pattern of letting non authenticated users use many features.

**Comment by jasonify** [comment]
Kinda, it's more like firebase's anonymous auth concept. The server can still keep track of your data and save your preferences, just not across devices.

**Comment by TheHollidayInn** [comment]
Sounds cool. I like the overall concept.
