### ISSUE TITLE
Topic Page Related Episode Bug

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#701]
Both of these topic pages got all the episodes about Spark added to both pages, even though one is about Container Orchestration:

https://www.softwaredaily.com/topic/apache-spark
https://www.softwaredaily.com/topic/container-orchestration-wars/

**Comment by marcosschlup** [comment]
@crablar it was added manually. I haven't put the automatic top into production yet

**Comment by marcosschlup** [comment]
@crablar Is this still needed?

**Comment by marcosschlup** [comment]
@crablar Is this still needed?

**Comment by crablar** [comment]
It looks correct at this point.
