### ISSUE TITLE
Tags and topic pages

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#706]
- [ ] editing tags on a post needs to be fixed
- [x] adding a tag to a post should add that post as a related episode on a topic page
- [x] same for removing the tag from a post
- [x] if a user adds a related episode to a topic page, that episode should add a tag for that topic
- [x] Topic pages should allow any user to add related episodes

**Comment by marcosschlup** [comment]
@crablar Changes are in production. 
I found no problem in adding and removing new or existing tags.
