### ISSUE TITLE
Add "Learn more" link on "Write on Software Daily" page"

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#716]
Clicking that link should launch a lightbox modal that says:

<Software Daily logo at the top>
If you are listening to lots of episodes of Software Daily, you can write about the topics in the show. It will help us grow our content, and help you retain information.

A topic page should be:
- brief (2-3 pages; you would want to read it on an airplane or on a short 15 minute commute)
- high-level (it should read like an executive summary, not a tutorial)
- informative (an unbiased presentation of the topic)

Here are a few examples:
[Container Orchestration Wars](https://www.softwaredaily.com/topic/container-orchestration-wars)
[Apache Spark](https://www.softwaredaily.com/topic/apache-spark)

**Comment by marcosschlup** [comment]
@crablar For this i'll change the text in page to 
```
We are looking for volunteer writers to summarize the topics on Software Daily.
If you want to write about a topic, you can select one or suggest your own topic.
```

**Comment by crablar** [comment]
@marcosschlup The modal lightbox should only include the information about writing guidelines. The search box and the list of topics should still be listed below "Learn More"

**Comment by marcosschlup** [comment]
@crablar Right. Will make the change
