### ISSUE TITLE
Search box should be rectangular by default; also it should not overlap with the "Subscribed" button

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#719]

**Comment by marcosschlup** [comment]
@crablar Search input should be aways visible? Or just with no rounded corners?

**Comment by crablar** [comment]
Always visible and with rounded corners.

**Comment by marcosschlup** [comment]
@crablar 
<img width="1047" alt="Captura de Tela 2020-04-06 às 11 43 27" src="https://user-images.githubusercontent.com/8609590/78570836-deff6e80-77fb-11ea-8103-219b5f00ed38.png">

<img width="1050" alt="Captura de Tela 2020-04-06 às 11 43 17" src="https://user-images.githubusercontent.com/8609590/78570817-dad35100-77fb-11ea-9ce5-afadf4c1b8ec.png">
