### ISSUE TITLE
Sharing a tweet from a highlight on a maintainer's page should add the maintainer's Twitter account, if they have one

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#738]

**Comment by marcosschlup** [comment]
<img width="592" alt="Captura de Tela 2020-04-20 às 14 54 31" src="https://user-images.githubusercontent.com/8609590/79783437-06cff580-8317-11ea-86f3-062f35e57490.png">

How about change this like a citation? `"This is bla bla..." - @SchlupMarcos`
We can add line breaks too
