### ISSUE TITLE
Twitter account episode association

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#739]
1. For each episode, [find the tweet associated with that episode from @software_daily](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline)
2. The users tagged in that field should be added to the Software Daily database associated with the episode; their Twitter accounts should be displayed to the right of "SE Daily" on the episode page (above "Listen to Podcast")
3. When an episode highlight is tweeted, the users tagged should be added to that tweet (ie Jeremy Daly would be tagged in a tweet from [this episode](https://www.softwaredaily.com/post/5e85ae801fa4d9000c00ee2e/Serverless-Development-with-Jeremy-Daly))

**Comment by marcosschlup** [comment]
@crablar 
<img width="1079" alt="Captura de Tela 2020-04-21 às 14 35 46" src="https://user-images.githubusercontent.com/8609590/79896951-64c81000-83df-11ea-80f2-83b47985424e.png">

---

<img width="995" alt="Captura de Tela 2020-04-21 às 14 47 43" src="https://user-images.githubusercontent.com/8609590/79896963-68f42d80-83df-11ea-9adb-cbff4de23e4a.png">

---

<img width="596" alt="Captura de Tela 2020-04-21 às 14 48 16" src="https://user-images.githubusercontent.com/8609590/79896973-6d204b00-83df-11ea-8f2e-2ae299c2737a.png">

**Comment by crablar** [comment]
@marcosschlup awesome. Nice work.

**Comment by crablar** [comment]
@marcosschlup I am noticing [many of the older episodes](https://www.softwaredaily.com/post/5913c0984ee01db33caccf20/Kafka-Event-Sourcing-with-Neha-Narkhede) do not have the Twitter accounts. Could you revisit this?

**Comment by marcosschlup** [comment]
@crablar unfortunately the Twitter API only brings the last 20 tweets

**Comment by crablar** [comment]
@marcosschlup can you try the 2014 answer and see if that works? https://stackoverflow.com/questions/4464116/how-to-get-more-than-20-results-with-the-twitter-search-api

**Comment by marcosschlup** [comment]
@crablar Yes. Will try that today

**Comment by marcosschlup** [comment]
@crablar It's done.
There are still a few episodes that haven't been updated because the text in the tweet is different from some pattern I found. See if it’s enough or if we should refine it further.
