### ISSUE TITLE
Improve Presentation of Scraped Content (or Improve Scraper)

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#74]
Would love to hear ideas/suggestions around this.

**Comment by edgar971** [comment]
Can you provide more information on this @crablar? I'm not sure what you mean by Improve Presentation of Scraped Content.

**Comment by crablar** [comment]
This has been solved. Originally the ads were displayed in these posts, but it looks like they have been cleaned out!
