### ISSUE TITLE
User's profile page should display their twitter

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#742]

**Comment by marcosschlup** [comment]
@crablar 
<img width="716" alt="Captura de Tela 2020-04-08 às 11 08 38" src="https://user-images.githubusercontent.com/8609590/78794421-1bf96b80-798a-11ea-92b5-6847b6b6d794.png">

Profile has the Twitter account (@marcossantos). Maybe it can be more visible

**Comment by crablar** [comment]
@marcosschlup this looks good!

**Comment by crablar** [comment]
@marcosschlup  Still not seeing it in production?

**Comment by marcosschlup** [comment]
@crablar Working now. It was not updating
