### ISSUE TITLE
Creating questions for blank topics

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#754]
Sorry for not handling this in the product design. 

Creating questions for a topic that has not been written yet should add those questions to a topic page. The topic page should have an empty area that allows the user to click and request to write the topic page.

**Comment by sterlingrules** [comment]
@crablar Is this all in admin? It looks like currently, you can add questions to an empty topic. Should you be able to visit an empty topic from the public side? Is there where a user might request to write the topic?

**Comment by marcosschlup** [comment]
I'm changing this behavior in admin.
When adding a question to a topic, if the topicPage doesn't  exist, one will be created with empty content. This may be enough for frontend changes

**Comment by crablar** [comment]
@marcosschlup That's correct. 

On the admin side, adding questions to an empty topic should create that topic. 

Once the topic page is created, it should have a place where someone can click to request to write the topic page.

**Comment by marcosschlup** [comment]
I believe that good behavior would be:
If a topic Page is like `published: false`, show only the questions.
If it does not have a maintainer, show option to request to edit.

Are we going to show these empty in the side menu?

**Comment by crablar** [comment]
Yes, the pages with open questions should appear on the left.
