### ISSUE TITLE
Left sidebar links should route to the /topic page if the topic has been created, instead of the /posts page

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#758]

**Comment by crablar** [comment]
@sterlingrules Still occurring when you click "Flux" on main page

**Comment by sterlingrules** [comment]
Yes, I am working on this task today.

**Comment by sterlingrules** [comment]
@crablar should _only_ topics with a `topicpage` display? Or should the topics currently in production display, and if there's a `/topic` page display that, otherwise display `/posts`?

**Comment by crablar** [comment]
@sterlingrules if there's a /topic page display that, otherwise display /posts
