### ISSUE TITLE
In Admin panel, add a "Users" section and give my account the ability to add additional admin

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#759]

**Comment by marcosschlup** [comment]
@crablar You are a admin today. We use that admin status for your actions. If others will be admin too, they will do everything that you have access to do? Like set others as admin?
We can create a SuperAdmin status just for you if we need to distinguish.

**Comment by crablar** [comment]
Yes--keep my account as only superadmin

**Comment by marcosschlup** [comment]
@crablar  What tasks should only you be able to do?
