### ISSUE TITLE
Tweeting from the highlight lightbox should tag the episode guests' Twitter accounts

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#771]

**Comment by sterlingrules** [comment]
@crablar where do I find the guest twitter accounts per episode? Should these be stored in the DB?

**Comment by marcosschlup** [comment]
@sterlingrules It's not just the guests, but the tweet users are in Post entity now,

<img width="259" alt="Captura de Tela 2020-05-05 às 14 44 37" src="https://user-images.githubusercontent.com/8609590/81097980-1175b780-8edf-11ea-9746-168444c87b47.png">

**Comment by sterlingrules** [comment]
@marcosschlup ah, great, thanks!
