### ISSUE TITLE
Some episode posts pull in wrong Twitter handles

### ISSUE THREAD

**Issue by erikawho** [SoftwareEngineeringDaily/sedaily-front-end#790]
<img width="731" alt="Screen Shot 2020-05-04 at 7 57 00 PM" src="https://user-images.githubusercontent.com/15097170/81135591-aa232c00-8f0d-11ea-8659-005a7a343b5c.png">
<img width="665" alt="Screen Shot 2020-05-04 at 8 43 47 PM" src="https://user-images.githubusercontent.com/15097170/81135602-b4452a80-8f0d-11ea-8a90-ffbf63d81bbf.png">

**Comment by marcosschlup** [comment]
@erikawho Hi! This is fixed now
