### ISSUE TITLE
Change "Write" page

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#797]
- [x] topic search box should be an autocomplete that searches through Topics
- [x] below that there should be the top 5 topic pages (in terms of number of episodes that have been created) that have not been written
- [x] below that there should be a list of 10 random questions that have not been answered

**Comment by crablar** [comment]
@sterlingrules 

On the "Write" page, also add an "Add company" or topic button.

Remove "Write on Software Daily
We are looking for volunteer writers to summarize the topics on Software Daily. If you want to write about one of the following topics, select the topic below or suggest your own topic." and the "Learn More" button.

The current search box should say "Write about an existing topic."

**Comment by sterlingrules** [comment]
@crablar let me know when you've had a chance to review these changes in staging

**Comment by crablar** [comment]
@sterlingrules 

- To be compatible with #822 , change the word "Request" to "Write"
- Remove the word "Topics" at the top
- The lightbox for creating a new topic should be the same on the "Write" page as on the left sidebar in the homepage
- Above the 5 suggested topics put "Suggested topics"

**Comment by sterlingrules** [comment]
@crablar made these adjustments in staging
