### ISSUE TITLE
"Name" Should Validate At Least 2 Words (first name + last name)

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#80]

**Comment by nhc** [comment]
Should we keep things very light or could we use something like this http://vee-validate.logaretm.com/ ?

Would we perhaps need other types of form validation in the future? Otherwise we just do a simple but crude check.

**Comment by crablar** [comment]
Either approach is great. There will likely be other validation in the future.
