### ISSUE TITLE
Unwritten Topic Page Changes

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#803]
- layout of the topic page should just have the topic name at the top, then remove "Write on Software Daily"
- remove "We are looking..." and change the "Click Here" link to say "Write Topic Page"
- below "Write Topic Page" add the "Learn More" link as "What is a topic page?" in smaller text
- below that add "Ask a question" (Any user should have ability to add a question)

**Comment by marcosschlup** [comment]
@crablar Today, this content is the same as `write` page. Shall we leave `write` page untouched?

**Comment by marcosschlup** [comment]
@crablar Just to confirm. Will we allow the user to change or delete his question?

**Comment by crablar** [comment]
> @crablar Today, this content is the same as write page. Shall we leave write page untouched?

On Write page, remove "Suggest new topic" and add the + Add new company or topic

> @crablar Just to confirm. Will we allow the user to change or delete his question?

Yes. The creator of a page should also be able to delete their page, as well as have access to the other maintainer abilities.
