### ISSUE TITLE
Add Company or Topic

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#805]
This feature is to allow users to create new pages for their company or topic. The idea is that projects and companies will post pages, and then we will interview the ones that are interesting. That way, there is an incentive for them to post information about their company/project so that they get publicity.

- remove "Most Popular"
- on the left hand side of the page, at the top add a button that says "+ Add Company or Topic"
- clicking it launches a blank topic page, with a modal that says "What is the name of your project?" and if the user types a topic that exists, they can't create it. Otherwise, it creates a new topic page with them as the maintainer.

**Comment by marcosschlup** [comment]
@crablar I believe it is a good idea to separate content from companies and topics technically (db). The ideal would be to put a selector for the person to indicate if he is going to write about a topic or about his company. If we do not do this, we will not be able to differentiate later in tags or even in the menu.

Can we put it in this initial modal?

**Comment by marcosschlup** [comment]
It is also important to know whether the contents of topics or companies will have any future differences. If so, I will assess whether we technically separate the two entities.

**Comment by crablar** [comment]
@marcosschlup Could you add an additional field to user-generated topics that is "user-generated=true"?

**Comment by marcosschlup** [comment]
@crablar for user generated yes. But for Company vs Topic, I still believe it is important

**Comment by marcosschlup** [comment]
@crablar To better explain my doubt.
Imagine that I as a user create a topic called x-team. If in the future we want to create the possibility of adding Jobs to this page, this should happen for a topic like x-team but not for a topic like Javascript. So we need to differentiate the two.
If we don't do that now, we will have a lot of work in the future, especially with existing topics.
In my view, the only way to differentiate is to make the user select what he will register at the beginning.

**Comment by marcosschlup** [comment]
Something like this

<img width="1030" alt="Captura de Tela 2020-05-11 às 14 54 03" src="https://user-images.githubusercontent.com/8609590/81594395-34004880-9397-11ea-9a77-1ce1c1e77188.png">

**Comment by crablar** [comment]
I understand the concern, but I would prefer to keep the data model simpler.

We will have jobs on a JavaScript page as well.
