### ISSUE TITLE
Changes to maintainer/topic page

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#822]
- anyone should be able to become a maintainer and start editing immediately, you should not need to get the email approval
- add admin ability to block someone as a maintainer
- keep revision history of the published topic pages

**Comment by marcosschlup** [comment]
@crablar 
Shall we block the user in general? Will he not be able to edit any topic or will we block his editing only in the related topic?

If we are going to put this block in admin / user or admin / topic

**Comment by crablar** [comment]
You can just prevent them from making edits to any topic.

**Comment by marcosschlup** [comment]
Ok, will put this like a "blocked edition" in `admin/users`
