### ISSUE TITLE
Existing user can't log in

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#824]
Copying his email here, this is concerning.

Hey Jeff - I just tried logging into Software Daily to finally finish up the topic pages for platform engineering and data pipelines.

I'm unable to access the account I was previously using.
I can't remember whether I used my nickthedaigler@gmail.com or nicholas.daigler@tufts.edu email to login.

The forgot my password page doesn't recognize either of these emails as associated with an account.

I tried signing up with nickthedaigler@gmail.com (I think this was the email associated with my account) to see if it would give me an error message, but it didn't. It let me create a new account with this email.

Is this expected behavior? I saw you posted an article about Software Daily, so I'm wondering if maybe you reset everything in anticipation for this expose.

**Comment by sterlingrules** [comment]
Looking into this now

**Comment by sterlingrules** [comment]
He was logging in with a different email. The account tied to the Topic Pages he's referring to are under this email: nicholas.daigler@gmail.com
