### ISSUE TITLE
Most recent two episodes of ad-free feed have ads

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#825]
@erikawho did the ad free files get uploaded correctly?

**Comment by marcosschlup** [comment]
@crablar @erikawho 
It looks like the `adfree` url doesn't exist or is in a different pattern.

First, the url changed for a secured url. There's a `/secure` in the mp3 url in the last 3 to 4 posts

Second, for this episode: 
`https://traffic.libsyn.com/secure/sedaily/2020_05_15_AWSVirtualization.mp3`
this adfree url should exist:
`https://traffic.libsyn.com/secure/sedaily/2020_05_15_AWSVirtualization_adfree.mp3`
but this last can't be found

**Comment by crablar** [comment]
@erikawho could you please check the pattern of the episode file title?

**Comment by erikawho** [comment]
This is what I see in AWS, hope this helps 
<img width="813" alt="Screen Shot 2020-05-19 at 10 17 39 AM" src="https://user-images.githubusercontent.com/15097170/82357566-27dd4200-99ba-11ea-9a09-710e59b8f6af.png">

**Comment by marcosschlup** [comment]
@erikawho @crablar 
We need the files to follow the same pattern as before. I don't know exactly what your process is and what has to change, but we really need it to come back, if that is an option.

Is it possible to look at previous posts and see how it was done?

**Comment by crablar** [comment]
@sterlingrules I am looping you in here because we need to figure out why the script is not grabbing the ad free episodes and putting them in the RSS feed.

**Comment by marcosschlup** [comment]
@erikawho @crablar 
Found a fix. 
Libsyn has now a different url that was in "conflict" with what the code expected. Just added a second option to the code. Thanks for the help
