### ISSUE TITLE
Publication date of episodes is not appearing correctly in RSS feed

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#826]
From a listener:

The publication date is showing wrong in Podcast Addict and I believe it might be related to the format you're using in the RSS feed (edited) 
4:19
<pubDate>
Sat May 16 2020 09:00:57 GMT+0000 (Coordinated Universal Time)
</pubDate>
 (edited) 
4:19
vs.
4:19
<pubDate>Sat, 16 May 2020 09:00:57 +0000</pubDate>
4:20
but I know nothing about RSS, so I might be totally wrong

**Comment by marcosschlup** [comment]
@crablar 
Just deployed a fix. A proper documented format for the pubDate.
Can you test now, please?

**Comment by crablar** [comment]
Looks OK.
