### ISSUE TITLE
Create separate RSS feed with ads, and all the episodes

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#838]
The endpoint can be https://software-enginnering-daily-api.herokuapp.com/api/rss/public/all_unlimited

**Comment by marcosschlup** [comment]
@crablar Are we going to show this link somewhere on the site?

**Comment by crablar** [comment]
@marcosschlup No, I just need it to submit to Google Podcasts.

**Comment by marcosschlup** [comment]
@crablar This is working now
