### ISSUE TITLE
Highlighted shares on topic pages should autofill with the creator's Twitter

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#842]

**Comment by marcosschlup** [comment]
@crablar 
Just to confirm.

<img width="619" alt="Captura de Tela 2020-05-25 às 16 36 14" src="https://user-images.githubusercontent.com/8609590/82839447-cb8c8d80-9ea5-11ea-926e-ff8727b7e030.png">

When sharing in Twitter what someone highlighted we want to change `Marcos left a highlight...` with `@SchlupMarcos left a highlight...`
Is that it?

**Comment by crablar** [comment]
@marcosschlup No, we are talking about Topic pages, such as ReactJS. When the author of a ReactJS page writes a topic, they should be tagged in the Tweet share.
