### ISSUE TITLE
Redesign main page to look like softwareengineeringdaily.com

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#872]
Let's move away from the feed format and create more of the newspaper-style website, still with infinite scroll, look that SED.com has

**Comment by sterlingrules** [comment]
A few questions:
- How many tags should be displayed in the header
- Should popular posts, be the most popular of all time? Or should they be trending, like the most popular in the last week or month?

**Comment by crablar** [comment]
- as many tags as fit in a responsive design
- most popular in the last month
