### ISSUE TITLE
Post created without audio 

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#881]
Thought we had a solution to this implemented.

https://www.softwaredaily.com/post/5ee9e082537be1000c6634b4/HTTP-with-Julia-Evans-Summer-Break-Repeat

**Comment by sterlingrules** [comment]
I had not been assigned these particular issues. however, I'll take a look and see what's happening.

**Comment by sterlingrules** [comment]
It seems the mp3 it references is not the same as what the miner is set up to look for. I've updated the miner to find these mp3's as well now.
