### ISSUE TITLE
Ad Blocker Issues

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#89]
![image](https://user-images.githubusercontent.com/1283090/32634945-feac1d4e-c562-11e7-8e77-f004f59b47fd.png)

**Comment by Tofuus** [comment]
I'm running Ublock and Chrome 62.0.3202.89. I was unable to replicate this.

**Comment by Tofuus** [comment]
swyx the reporter of the issue mentioned he uses privacy badger. That may be the cause of the issue.
