### ISSUE TITLE
Save listened progress of podcast

### ISSUE THREAD

**Issue by edgar971** [SoftwareEngineeringDaily/sedaily-front-end#94]
It would be nice to save the progress of the currently listening podcast locally on the browser. I had an issue today where I reloaded the browser and lost my current progress :/. Here is what I was thinking: 

User clicks to listen to a podcast --> Progress is saved locally 

User comes back to the site --> Checks if progress is saved locally and displays the player with the last saved progress. 

Does that make sense? I would like to hear your thoughts

**Comment by crablar** [comment]
We should have something like this. I'm wondering how many people listen to podcasts on the web -> how important this is.

@edgar971 do you regularly listen to podcasts on a web site?

**Comment by jasonify** [comment]
This is great. I was thinking eventually we could expand this to the backend and have it sync your listened to progress.. which we might already be doing, I'll have to look more into that but I remember we had some issues around that.
